In [1]:
import pandas as pd
import numpy as np
import plotly as py
import seaborn as sb
%matplotlib inline
import xlrd

In [2]:
ge2009 = pd.ExcelFile('GE2009.xls')

In [3]:
ge09el = ge2009.parse('electors')

In [4]:
ge09el.columns = ge09el.iloc[2]
ge09el.reindex(ge09el.index.drop(2))

2,STATE CODE,STATE,PC NO,PARLIAMENTARY CONSTITUENCY,Total voters,Total_Electors,TOT_CONTESTANT,POLL PERCENTAGE
0,GENERAL ELECTION 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S01,Andhra Pradesh,1,Adilabad,864165,1131211,9,76.3929
4,S01,Andhra Pradesh,2,Peddapalle,905332,1315642,15,68.8129
5,S01,Andhra Pradesh,3,Karimnagar,990646,1496211,15,66.2103
6,S01,Andhra Pradesh,4,Nizamabad,891508,1333271,12,66.8662
7,S01,Andhra Pradesh,5,Zahirabad,1017372,1359566,10,74.8306
8,S01,Andhra Pradesh,6,Medak,1061993,1389721,9,76.4177
9,S01,Andhra Pradesh,7,Malkajgiri,1206223,2343050,19,51.4809
10,S01,Andhra Pradesh,8,Secundrabad,865357,1574818,23,54.9497
11,S01,Andhra Pradesh,9,Hyderabad,732212,1393242,23,52.5545
12,S01,Andhra Pradesh,10,CHELVELLA,1086510,1681664,15,64.6092
13,S01,Andhra Pradesh,11,Mahbubnagar,927422,1368868,32,67.751
14,S01,Andhra Pradesh,12,Nagarkurnool,1026444,1460484,13,70.2811
15,S01,Andhra Pradesh,13,Nalgonda,1079189,1455016,14,74.1702
16,S01,Andhra Pradesh,14,Bhongir,1129421,1478391,15,76.3953
17,S01,Andhra Pradesh,15,Warangal,1031172,1486617,15,69.3637
18,S01,Andhra Pradesh,16,Mahabubabad,997815,1265396,12,78.854
19,S01,Andhra Pradesh,17,Khammam,1034532,1259815,13,82.1178
20,S01,Andhra Pradesh,18,Aruku,792793,1182514,11,67.043
21,S01,Andhra Pradesh,19,Srikakulam,920282,1226125,6,75.0561
22,S01,Andhra Pradesh,20,Vizianagaram,1019868,1323238,9,77.0737
23,S01,Andhra Pradesh,21,Visakhapatnam,1012261,1387482,15,72.9567
24,S01,Andhra Pradesh,22,Anakapalli,1049207,1331695,10,78.7873
25,S01,Andhra Pradesh,23,Kakinada,967294,1265094,16,76.4602
26,S01,Andhra Pradesh,24,Amalapuram,1023809,1275287,11,80.2807
27,S01,Andhra Pradesh,25,Rajahmundry,1018762,1260974,13,80.7917
28,S01,Andhra Pradesh,26,Narsapuram,992405,1173138,10,84.5941
29,S01,Andhra Pradesh,27,Eluru,1079062,1275575,12,84.5942
30,S01,Andhra Pradesh,28,Machilipatnam,1046522,1251053,10,83.6513
...,...,...,...,...,...,...,...,...
516,S27,Jharkhand,3,Godda,798642,1412253,23,56.5509
517,S27,Jharkhand,4,Chatra,473961,1037665,11,45.6757
518,S27,Jharkhand,5,Kodarma,780540,1390428,16,56.1367
519,S27,Jharkhand,6,Giridih,619192,1346527,17,45.9844
520,S27,Jharkhand,7,Dhanbad,814297,1806475,32,45.0766
521,S27,Jharkhand,8,Ranchi,724390,1625148,26,44.5738
522,S27,Jharkhand,9,Jamshedpur,705571,1380279,26,51.118
523,S27,Jharkhand,10,Singhbhum,581827,957406,9,60.7712
524,S27,Jharkhand,11,Khunti,510352,980868,9,52.0307
525,S27,Jharkhand,12,Lohardaga,524417,981666,15,53.4211
526,S27,Jharkhand,13,Palamau,651582,1417375,21,45.971
527,S27,Jharkhand,14,Hazaribagh,690958,1301651,13,53.0832
528,S28,Uttarakhand,1,Tehri Garhwal,585006,1159691,18,50.445
529,S28,Uttarakhand,2,Garhwal,537004,1092282,13,49.1635
530,S28,Uttarakhand,3,Almora,481451,1057379,10,45.5325
531,S28,Uttarakhand,4,Nainital-udhamsingh Nagar,753956,1284092,14,58.7151
532,S28,Uttarakhand,5,Hardwar,788401,1294280,21,60.9143
533,U01,Andaman & Nicobar Islands,1,Andaman & nicobar islands,170103,265108,11,64.1637
534,U02,Chandigarh,1,Chandigarh,343558,524444,14,65.509
535,U03,Dadra & Nagar Haveli,1,Dadar & Nagar Haveli,110363,150704,5,73.2316
536,U04,Daman & Diu,1,Daman & diu,68025,95382,7,71.3185
537,U05,NCT OF Delhi,1,CHANDNI CHOWK,780446,1413535,41,55.2124
538,U05,NCT OF Delhi,2,NORTH EAST DELHI,878426,1677058,16,52.379
539,U05,NCT OF Delhi,3,EAST DELHI,857432,1604795,17,53.4294
540,U05,NCT OF Delhi,4,NEW DELHI,765022,1373146,40,55.7131
541,U05,NCT OF Delhi,5,NORTH WEST DELHI,857545,1798181,16,47.6896
542,U05,NCT OF Delhi,6,WEST DELHI,884168,1687727,15,52.3881
543,U05,NCT OF Delhi,7,SOUTH DELHI,731314,1542412,15,47.4137
544,U06,Lakshadweep,1,Lakshadweep,39498,45983,4,85.897
545,U07,Puducherry,1,Puducherry,608509,762440,28,79.8107

In [6]:
ge09el.drop(0, inplace = True)
ge09el.drop(1, inplace = True)
ge09el.drop(2, inplace = True)
ge09el.reset_index(inplace=True)

In [7]:
del ge09el['index']

In [8]:
ge09el.columns

Index(['STATE CODE', 'STATE', 'PC NO', 'PARLIAMENTARY CONSTITUENCY',
       'Total voters', 'Total_Electors', 'TOT_CONTESTANT', 'POLL PERCENTAGE'],
      dtype='object', name=2)

In [9]:
s2009 = pd.pivot_table(ge09el,index='STATE',values=['Total voters', 'Total_Electors', 'TOT_CONTESTANT'],aggfunc=sum)

In [12]:
s2009['POLL_PERC in %']=(s2009['Total voters']/s2009['Total_Electors']*100)

In [13]:
s2009

2,TOT_CONTESTANT,Total voters,Total_Electors,POLL_PERC in %
STATE,,,,
Andaman & Nicobar Islands,11,170103,265108,64.163662
Andhra Pradesh,569,42083881,57892259,72.693451
Arunachal Pradesh,8,500649,734541,68.158074
Assam,158,12148928,17470329,69.540350
Bihar,672,24236704,54505246,44.466736
Chandigarh,14,343558,524444,65.508996
Chattisgarh,178,8556920,15476577,55.289487
Dadra & Nagar Haveli,5,110363,150704,73.231633
Daman & Diu,7,68025,95382,71.318488
Goa,18,564439,1020794,55.294114
Gujarat,359,17476567,36484281,47.901635
Haryana,210,8160347,12087710,67.509454
Himachal Pradesh,31,2691573,4606674,58.427686
Jammu & Kashmir,81,2609249,6572896,39.697099
Jharkhand,249,9142643,17934095,50.979115
Karnataka,427,24581348,41790939,58.819803
Kerala,217,16041499,21859536,73.384444
Lakshadweep,4,39498,45983,85.896962
Madhya Pradesh,429,19488631,38085179,51.171168
Maharashtra,819,37007318,72954058,50.726881
Manipur,16,1342309,1736251,77.310769
Meghalaya,11,822614,1277739,64.380441
Mizoram,4,326424,629374,51.864869
NCT OF Delhi,160,5754353,11096854,51.855715
Nagaland,3,1189742,1321878,90.003919
Orissa,157,17772023,27194864,65.350660
Puducherry,28,608509,762440,79.810739
Punjab,218,11833883,16958380,69.781919
Rajasthan,346,17942008,37060011,48.413391
Sikkim,7,252274,300584,83.927954
Tamil Nadu,823,30404136,41620460,73.050937
Tripura,19,1760485,2082265,84.546636
Uttar Pradesh,1368,55434443,116006374,47.785687
Uttarakhand,76,3145818,5887724,53.430120
West Bengal,368,42740385,52493168,81.420853

In [19]:
ge09cw = ge2009.parse('Cand_Wise')

In [21]:
ge09cw.columns = ge09cw.iloc[4]
ge09cw.reindex(ge09cw.index.drop(4))

4,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,GENERAL ELECTION 2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD RAMESH,M,ST,43,TDP,372268,1
6,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,KOTNAK RAMESH,M,ST,39,INC,257181,2
7,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,MESRAM NAGO RAO,M,ST,59,PRAP,112930,3
8,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ADE TUKARAM,M,ST,55,BJP,57931,4
9,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD SADASHIV NAIK,M,ST,50,BSP,16471,5
10,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,BANKA SAHADEVU,M,ST,55,IND,16441,6
11,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,GANTA PENTANNA,M,ST,36,IND,13378,7
12,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,NETHAVAT RAMDAS,M,ST,39,IND,9157,8
13,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ATHRAM LAXMAN RAO,M,ST,47,IND,7824,9
14,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,DR.G.VIVEKANAND,M,SC,51,INC,313748,1
15,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GOMASA SRINIVAS,M,SC,41,TRS,264731,2
16,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AREPELLI DAVID RAJU,M,SC,36,PRAP,175605,3
17,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,MATHANGI NARSIAH,M,SC,64,BJP,67836,4
18,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,S.LAXMAIAH,M,SC,41,IND,20263,5
19,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GAJJELA SWAMY,M,SC,49,BSP,15859,6
20,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AMBALA MAHENDAR,M,SC,38,IND,8364,7
21,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,G.VINAY KUMAR,M,SC,51,IND,6726,8
22,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,KRISHNA SABBALI,M,SC,39,MCPI(S),5752,9
23,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,D. RAMULU,M,SC,51,IND,5511,10
24,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,B. MALLAIAH,M,SC,32,IND,4541,11
25,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,NALLALA KANUKAIAH,M,SC,39,IND,4468,12
26,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,A. KAMALAMMA,F,SC,36,IND,3938,13
27,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GORRE RAMESH,M,SC,42,IND,3414,14
28,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,K. RAJASWARI,F,SC,38,IND,3328,15
29,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,41,INC,317927,1
30,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,49,TRS,267684,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8045,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,M.K. LUKMANUL HAKEEM,M,ST,32,CPM,467,3
8046,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,DR. K. P. MUTHUKOYA,M,ST,57,BJP,245,4
8047,U07,Puducherry,3,2009,1,Puducherry,GEN,NARAYANASAMY,M,GEN,61,INC,300391,1
8048,U07,Puducherry,3,2009,1,Puducherry,GEN,RAMADASS. M,M,GEN,59,PMK,208619,2
8049,U07,Puducherry,3,2009,1,Puducherry,GEN,K.A.U. ASANAA,M,GEN,54,DMDK,52638,3
8050,U07,Puducherry,3,2009,1,Puducherry,GEN,VISWESWARAN. M,M,GEN,56,BJP,13442,4
8051,U07,Puducherry,3,2009,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,32,IND,5103,5
8052,U07,Puducherry,3,2009,1,Puducherry,GEN,V. LINGAMURTHY,M,GEN,60,IND,4179,6
8053,U07,Puducherry,3,2009,1,Puducherry,GEN,M. SOMASUNDARAM,M,SC,48,BSP,3697,7
8054,U07,Puducherry,3,2009,1,Puducherry,GEN,SIVARAMAN. V,M,GEN,32,IND,2439,8
8055,U07,Puducherry,3,2009,1,Puducherry,GEN,KALIAMURTHY. K,M,SC,40,IND,2074,9
8056,U07,Puducherry,3,2009,1,Puducherry,GEN,A. SENKADIR,M,GEN,35,IND,1896,10
8057,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAJENDRAN,M,GEN,40,IND,1810,11
8058,U07,Puducherry,3,2009,1,Puducherry,GEN,MANIMARAN,M,GEN,31,IND,1532,12
8059,U07,Puducherry,3,2009,1,Puducherry,GEN,V. SARAVANAN,M,SC,36,IND,1425,13
8060,U07,Puducherry,3,2009,1,Puducherry,GEN,VEERAMUTHU. A,M,GEN,34,IND,1239,14
8061,U07,Puducherry,3,2009,1,Puducherry,GEN,S. BALASUBRAMANIAN,M,GEN,50,CPI(ML)(L),839,15
8062,U07,Puducherry,3,2009,1,Puducherry,GEN,G. SUBRAMANIYAN,M,GEN,36,IND,757,16
8063,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAMAMURTHY,M,GEN,45,IND,662,17
8064,U07,Puducherry,3,2009,1,Puducherry,GEN,A. RAJASEKAR,M,GEN,27,LJP,656,18
8065,U07,Puducherry,3,2009,1,Puducherry,GEN,PRADEEP ANIRUDDH,M,GEN,29,PPOI,627,19
8066,U07,Puducherry,3,2009,1,Puducherry,GEN,ARUNACHALAM. K,M,SC,32,IND,597,20
8067,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GOVINDASAMY,M,GEN,59,KDC,570,21
8068,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GNANAVEL,M,SC,38,JMM,456,22
8069,U07,Puducherry,3,2009,1,Puducherry,GEN,P. VIJAYABASKAR,M,GEN,32,IND,449,23
8070,U07,Puducherry,3,2009,1,Puducherry,GEN,DR. R. NARAYANAN,M,GEN,59,IND,422,24
8071,U07,Puducherry,3,2009,1,Puducherry,GEN,MUPPADAI MATHIMAHARAJA,M,GEN,45,IND,378,25
8072,U07,Puducherry,3,2009,1,Puducherry,GEN,MURUGAIYAN. K.S,M,GEN,42,IND,378,26
8073,U07,Puducherry,3,2009,1,Puducherry,GEN,I.M. SEKAR,M,GEN,46,IND,375,27
8074,U07,Puducherry,3,2009,1,Puducherry,GEN,MOHAMED YOUSUF. S.A,M,GEN,46,IND,298,28

In [22]:
ge09cw.drop(0, inplace = True)
ge09cw.drop(1, inplace = True)
ge09cw.drop(2, inplace = True)
ge09cw.drop(3, inplace = True)

In [23]:
ge09cw.drop(4, inplace = True)
ge09cw.reset_index(inplace=True)

In [24]:
del ge09cw['index']

In [25]:
ge09cwge99cw.reset_index(inplace=True)

4,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD RAMESH,M,ST,43,TDP,372268,1
1,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,KOTNAK RAMESH,M,ST,39,INC,257181,2
2,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,MESRAM NAGO RAO,M,ST,59,PRAP,112930,3
3,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ADE TUKARAM,M,ST,55,BJP,57931,4
4,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD SADASHIV NAIK,M,ST,50,BSP,16471,5
5,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,BANKA SAHADEVU,M,ST,55,IND,16441,6
6,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,GANTA PENTANNA,M,ST,36,IND,13378,7
7,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,NETHAVAT RAMDAS,M,ST,39,IND,9157,8
8,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ATHRAM LAXMAN RAO,M,ST,47,IND,7824,9
9,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,DR.G.VIVEKANAND,M,SC,51,INC,313748,1
10,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GOMASA SRINIVAS,M,SC,41,TRS,264731,2
11,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AREPELLI DAVID RAJU,M,SC,36,PRAP,175605,3
12,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,MATHANGI NARSIAH,M,SC,64,BJP,67836,4
13,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,S.LAXMAIAH,M,SC,41,IND,20263,5
14,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GAJJELA SWAMY,M,SC,49,BSP,15859,6
15,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AMBALA MAHENDAR,M,SC,38,IND,8364,7
16,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,G.VINAY KUMAR,M,SC,51,IND,6726,8
17,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,KRISHNA SABBALI,M,SC,39,MCPI(S),5752,9
18,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,D. RAMULU,M,SC,51,IND,5511,10
19,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,B. MALLAIAH,M,SC,32,IND,4541,11
20,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,NALLALA KANUKAIAH,M,SC,39,IND,4468,12
21,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,A. KAMALAMMA,F,SC,36,IND,3938,13
22,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GORRE RAMESH,M,SC,42,IND,3414,14
23,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,K. RAJASWARI,F,SC,38,IND,3328,15
24,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,41,INC,317927,1
25,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,49,TRS,267684,2
26,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VELICHALA RAJENDER RAO,M,GEN,32,PRAP,175582,3
27,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,CHANDUPATLA JANGA REDDY,M,GEN,75,BJP,122337,4
28,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,BARIGE GATTAIAH YADAV,M,GEN,32,IND,26026,5
29,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VIRESHAM NALIMELA,M,GEN,58,BSP,16332,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,M.K. LUKMANUL HAKEEM,M,ST,32,CPM,467,3
8041,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,DR. K. P. MUTHUKOYA,M,ST,57,BJP,245,4
8042,U07,Puducherry,3,2009,1,Puducherry,GEN,NARAYANASAMY,M,GEN,61,INC,300391,1
8043,U07,Puducherry,3,2009,1,Puducherry,GEN,RAMADASS. M,M,GEN,59,PMK,208619,2
8044,U07,Puducherry,3,2009,1,Puducherry,GEN,K.A.U. ASANAA,M,GEN,54,DMDK,52638,3
8045,U07,Puducherry,3,2009,1,Puducherry,GEN,VISWESWARAN. M,M,GEN,56,BJP,13442,4
8046,U07,Puducherry,3,2009,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,32,IND,5103,5
8047,U07,Puducherry,3,2009,1,Puducherry,GEN,V. LINGAMURTHY,M,GEN,60,IND,4179,6
8048,U07,Puducherry,3,2009,1,Puducherry,GEN,M. SOMASUNDARAM,M,SC,48,BSP,3697,7
8049,U07,Puducherry,3,2009,1,Puducherry,GEN,SIVARAMAN. V,M,GEN,32,IND,2439,8
8050,U07,Puducherry,3,2009,1,Puducherry,GEN,KALIAMURTHY. K,M,SC,40,IND,2074,9
8051,U07,Puducherry,3,2009,1,Puducherry,GEN,A. SENKADIR,M,GEN,35,IND,1896,10
8052,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAJENDRAN,M,GEN,40,IND,1810,11
8053,U07,Puducherry,3,2009,1,Puducherry,GEN,MANIMARAN,M,GEN,31,IND,1532,12
8054,U07,Puducherry,3,2009,1,Puducherry,GEN,V. SARAVANAN,M,SC,36,IND,1425,13
8055,U07,Puducherry,3,2009,1,Puducherry,GEN,VEERAMUTHU. A,M,GEN,34,IND,1239,14
8056,U07,Puducherry,3,2009,1,Puducherry,GEN,S. BALASUBRAMANIAN,M,GEN,50,CPI(ML)(L),839,15
8057,U07,Puducherry,3,2009,1,Puducherry,GEN,G. SUBRAMANIYAN,M,GEN,36,IND,757,16
8058,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAMAMURTHY,M,GEN,45,IND,662,17
8059,U07,Puducherry,3,2009,1,Puducherry,GEN,A. RAJASEKAR,M,GEN,27,LJP,656,18
8060,U07,Puducherry,3,2009,1,Puducherry,GEN,PRADEEP ANIRUDDH,M,GEN,29,PPOI,627,19
8061,U07,Puducherry,3,2009,1,Puducherry,GEN,ARUNACHALAM. K,M,SC,32,IND,597,20
8062,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GOVINDASAMY,M,GEN,59,KDC,570,21
8063,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GNANAVEL,M,SC,38,JMM,456,22
8064,U07,Puducherry,3,2009,1,Puducherry,GEN,P. VIJAYABASKAR,M,GEN,32,IND,449,23
8065,U07,Puducherry,3,2009,1,Puducherry,GEN,DR. R. NARAYANAN,M,GEN,59,IND,422,24
8066,U07,Puducherry,3,2009,1,Puducherry,GEN,MUPPADAI MATHIMAHARAJA,M,GEN,45,IND,378,25
8067,U07,Puducherry,3,2009,1,Puducherry,GEN,MURUGAIYAN. K.S,M,GEN,42,IND,378,26
8068,U07,Puducherry,3,2009,1,Puducherry,GEN,I.M. SEKAR,M,GEN,46,IND,375,27
8069,U07,Puducherry,3,2009,1,Puducherry,GEN,MOHAMED YOUSUF. S.A,M,GEN,46,IND,298,28

In [27]:
ge09cw.reset_index(inplace=True)

In [30]:
ge09cw.columns

Index(['index', 'ST_CODE', 'State name', 'Month', 'Year', 'PC Number',
       'PC name', 'PC Type', 'Candidate Name', 'Candidate Sex',
       'Candidate Category', 'Candidate Age', 'Party Abbreviation',
       'Total Votes Polled', 'Position'],
      dtype='object', name=4)

In [31]:
del ge09cw['index']

In [32]:
ge09cw

4,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD RAMESH,M,ST,43,TDP,372268,1
1,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,KOTNAK RAMESH,M,ST,39,INC,257181,2
2,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,MESRAM NAGO RAO,M,ST,59,PRAP,112930,3
3,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ADE TUKARAM,M,ST,55,BJP,57931,4
4,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD SADASHIV NAIK,M,ST,50,BSP,16471,5
5,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,BANKA SAHADEVU,M,ST,55,IND,16441,6
6,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,GANTA PENTANNA,M,ST,36,IND,13378,7
7,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,NETHAVAT RAMDAS,M,ST,39,IND,9157,8
8,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ATHRAM LAXMAN RAO,M,ST,47,IND,7824,9
9,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,DR.G.VIVEKANAND,M,SC,51,INC,313748,1
10,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GOMASA SRINIVAS,M,SC,41,TRS,264731,2
11,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AREPELLI DAVID RAJU,M,SC,36,PRAP,175605,3
12,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,MATHANGI NARSIAH,M,SC,64,BJP,67836,4
13,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,S.LAXMAIAH,M,SC,41,IND,20263,5
14,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GAJJELA SWAMY,M,SC,49,BSP,15859,6
15,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AMBALA MAHENDAR,M,SC,38,IND,8364,7
16,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,G.VINAY KUMAR,M,SC,51,IND,6726,8
17,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,KRISHNA SABBALI,M,SC,39,MCPI(S),5752,9
18,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,D. RAMULU,M,SC,51,IND,5511,10
19,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,B. MALLAIAH,M,SC,32,IND,4541,11
20,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,NALLALA KANUKAIAH,M,SC,39,IND,4468,12
21,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,A. KAMALAMMA,F,SC,36,IND,3938,13
22,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GORRE RAMESH,M,SC,42,IND,3414,14
23,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,K. RAJASWARI,F,SC,38,IND,3328,15
24,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,41,INC,317927,1
25,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,49,TRS,267684,2
26,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VELICHALA RAJENDER RAO,M,GEN,32,PRAP,175582,3
27,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,CHANDUPATLA JANGA REDDY,M,GEN,75,BJP,122337,4
28,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,BARIGE GATTAIAH YADAV,M,GEN,32,IND,26026,5
29,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VIRESHAM NALIMELA,M,GEN,58,BSP,16332,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,M.K. LUKMANUL HAKEEM,M,ST,32,CPM,467,3
8041,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,DR. K. P. MUTHUKOYA,M,ST,57,BJP,245,4
8042,U07,Puducherry,3,2009,1,Puducherry,GEN,NARAYANASAMY,M,GEN,61,INC,300391,1
8043,U07,Puducherry,3,2009,1,Puducherry,GEN,RAMADASS. M,M,GEN,59,PMK,208619,2
8044,U07,Puducherry,3,2009,1,Puducherry,GEN,K.A.U. ASANAA,M,GEN,54,DMDK,52638,3
8045,U07,Puducherry,3,2009,1,Puducherry,GEN,VISWESWARAN. M,M,GEN,56,BJP,13442,4
8046,U07,Puducherry,3,2009,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,32,IND,5103,5
8047,U07,Puducherry,3,2009,1,Puducherry,GEN,V. LINGAMURTHY,M,GEN,60,IND,4179,6
8048,U07,Puducherry,3,2009,1,Puducherry,GEN,M. SOMASUNDARAM,M,SC,48,BSP,3697,7
8049,U07,Puducherry,3,2009,1,Puducherry,GEN,SIVARAMAN. V,M,GEN,32,IND,2439,8
8050,U07,Puducherry,3,2009,1,Puducherry,GEN,KALIAMURTHY. K,M,SC,40,IND,2074,9
8051,U07,Puducherry,3,2009,1,Puducherry,GEN,A. SENKADIR,M,GEN,35,IND,1896,10
8052,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAJENDRAN,M,GEN,40,IND,1810,11
8053,U07,Puducherry,3,2009,1,Puducherry,GEN,MANIMARAN,M,GEN,31,IND,1532,12
8054,U07,Puducherry,3,2009,1,Puducherry,GEN,V. SARAVANAN,M,SC,36,IND,1425,13
8055,U07,Puducherry,3,2009,1,Puducherry,GEN,VEERAMUTHU. A,M,GEN,34,IND,1239,14
8056,U07,Puducherry,3,2009,1,Puducherry,GEN,S. BALASUBRAMANIAN,M,GEN,50,CPI(ML)(L),839,15
8057,U07,Puducherry,3,2009,1,Puducherry,GEN,G. SUBRAMANIYAN,M,GEN,36,IND,757,16
8058,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAMAMURTHY,M,GEN,45,IND,662,17
8059,U07,Puducherry,3,2009,1,Puducherry,GEN,A. RAJASEKAR,M,GEN,27,LJP,656,18
8060,U07,Puducherry,3,2009,1,Puducherry,GEN,PRADEEP ANIRUDDH,M,GEN,29,PPOI,627,19
8061,U07,Puducherry,3,2009,1,Puducherry,GEN,ARUNACHALAM. K,M,SC,32,IND,597,20
8062,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GOVINDASAMY,M,GEN,59,KDC,570,21
8063,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GNANAVEL,M,SC,38,JMM,456,22
8064,U07,Puducherry,3,2009,1,Puducherry,GEN,P. VIJAYABASKAR,M,GEN,32,IND,449,23
8065,U07,Puducherry,3,2009,1,Puducherry,GEN,DR. R. NARAYANAN,M,GEN,59,IND,422,24
8066,U07,Puducherry,3,2009,1,Puducherry,GEN,MUPPADAI MATHIMAHARAJA,M,GEN,45,IND,378,25
8067,U07,Puducherry,3,2009,1,Puducherry,GEN,MURUGAIYAN. K.S,M,GEN,42,IND,378,26
8068,U07,Puducherry,3,2009,1,Puducherry,GEN,I.M. SEKAR,M,GEN,46,IND,375,27
8069,U07,Puducherry,3,2009,1,Puducherry,GEN,MOHAMED YOUSUF. S.A,M,GEN,46,IND,298,28

In [35]:
ge09cw.to_csv('CW2009.csv',index=False)

In [36]:
cw=pd.read_csv('CW2009.csv')

In [37]:
cw

,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD RAMESH,M,ST,43,TDP,372268,1
1,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,KOTNAK RAMESH,M,ST,39,INC,257181,2
2,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,MESRAM NAGO RAO,M,ST,59,PRAP,112930,3
3,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ADE TUKARAM,M,ST,55,BJP,57931,4
4,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,RATHOD SADASHIV NAIK,M,ST,50,BSP,16471,5
5,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,BANKA SAHADEVU,M,ST,55,IND,16441,6
6,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,GANTA PENTANNA,M,ST,36,IND,13378,7
7,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,NETHAVAT RAMDAS,M,ST,39,IND,9157,8
8,S01,Andhra Pradesh,3,2009,1,Adilabad,ST,ATHRAM LAXMAN RAO,M,ST,47,IND,7824,9
9,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,DR.G.VIVEKANAND,M,SC,51,INC,313748,1
10,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GOMASA SRINIVAS,M,SC,41,TRS,264731,2
11,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AREPELLI DAVID RAJU,M,SC,36,PRAP,175605,3
12,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,MATHANGI NARSIAH,M,SC,64,BJP,67836,4
13,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,S.LAXMAIAH,M,SC,41,IND,20263,5
14,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GAJJELA SWAMY,M,SC,49,BSP,15859,6
15,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,AMBALA MAHENDAR,M,SC,38,IND,8364,7
16,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,G.VINAY KUMAR,M,SC,51,IND,6726,8
17,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,KRISHNA SABBALI,M,SC,39,MCPI(S),5752,9
18,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,D. RAMULU,M,SC,51,IND,5511,10
19,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,B. MALLAIAH,M,SC,32,IND,4541,11
20,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,NALLALA KANUKAIAH,M,SC,39,IND,4468,12
21,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,A. KAMALAMMA,F,SC,36,IND,3938,13
22,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,GORRE RAMESH,M,SC,42,IND,3414,14
23,S01,Andhra Pradesh,3,2009,2,Peddapalle,SC,K. RAJASWARI,F,SC,38,IND,3328,15
24,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,41,INC,317927,1
25,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,49,TRS,267684,2
26,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VELICHALA RAJENDER RAO,M,GEN,32,PRAP,175582,3
27,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,CHANDUPATLA JANGA REDDY,M,GEN,75,BJP,122337,4
28,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,BARIGE GATTAIAH YADAV,M,GEN,32,IND,26026,5
29,S01,Andhra Pradesh,3,2009,3,Karimnagar,GEN,VIRESHAM NALIMELA,M,GEN,58,BSP,16332,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,M.K. LUKMANUL HAKEEM,M,ST,32,CPM,467,3
8041,U06,Lakshadweep,3,2009,1,Lakshadweep,ST,DR. K. P. MUTHUKOYA,M,ST,57,BJP,245,4
8042,U07,Puducherry,3,2009,1,Puducherry,GEN,NARAYANASAMY,M,GEN,61,INC,300391,1
8043,U07,Puducherry,3,2009,1,Puducherry,GEN,RAMADASS. M,M,GEN,59,PMK,208619,2
8044,U07,Puducherry,3,2009,1,Puducherry,GEN,K.A.U. ASANAA,M,GEN,54,DMDK,52638,3
8045,U07,Puducherry,3,2009,1,Puducherry,GEN,VISWESWARAN. M,M,GEN,56,BJP,13442,4
8046,U07,Puducherry,3,2009,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,32,IND,5103,5
8047,U07,Puducherry,3,2009,1,Puducherry,GEN,V. LINGAMURTHY,M,GEN,60,IND,4179,6
8048,U07,Puducherry,3,2009,1,Puducherry,GEN,M. SOMASUNDARAM,M,SC,48,BSP,3697,7
8049,U07,Puducherry,3,2009,1,Puducherry,GEN,SIVARAMAN. V,M,GEN,32,IND,2439,8
8050,U07,Puducherry,3,2009,1,Puducherry,GEN,KALIAMURTHY. K,M,SC,40,IND,2074,9
8051,U07,Puducherry,3,2009,1,Puducherry,GEN,A. SENKADIR,M,GEN,35,IND,1896,10
8052,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAJENDRAN,M,GEN,40,IND,1810,11
8053,U07,Puducherry,3,2009,1,Puducherry,GEN,MANIMARAN,M,GEN,31,IND,1532,12
8054,U07,Puducherry,3,2009,1,Puducherry,GEN,V. SARAVANAN,M,SC,36,IND,1425,13
8055,U07,Puducherry,3,2009,1,Puducherry,GEN,VEERAMUTHU. A,M,GEN,34,IND,1239,14
8056,U07,Puducherry,3,2009,1,Puducherry,GEN,S. BALASUBRAMANIAN,M,GEN,50,CPI(ML)(L),839,15
8057,U07,Puducherry,3,2009,1,Puducherry,GEN,G. SUBRAMANIYAN,M,GEN,36,IND,757,16
8058,U07,Puducherry,3,2009,1,Puducherry,GEN,V. RAMAMURTHY,M,GEN,45,IND,662,17
8059,U07,Puducherry,3,2009,1,Puducherry,GEN,A. RAJASEKAR,M,GEN,27,LJP,656,18
8060,U07,Puducherry,3,2009,1,Puducherry,GEN,PRADEEP ANIRUDDH,M,GEN,29,PPOI,627,19
8061,U07,Puducherry,3,2009,1,Puducherry,GEN,ARUNACHALAM. K,M,SC,32,IND,597,20
8062,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GOVINDASAMY,M,GEN,59,KDC,570,21
8063,U07,Puducherry,3,2009,1,Puducherry,GEN,S. GNANAVEL,M,SC,38,JMM,456,22
8064,U07,Puducherry,3,2009,1,Puducherry,GEN,P. VIJAYABASKAR,M,GEN,32,IND,449,23
8065,U07,Puducherry,3,2009,1,Puducherry,GEN,DR. R. NARAYANAN,M,GEN,59,IND,422,24
8066,U07,Puducherry,3,2009,1,Puducherry,GEN,MUPPADAI MATHIMAHARAJA,M,GEN,45,IND,378,25
8067,U07,Puducherry,3,2009,1,Puducherry,GEN,MURUGAIYAN. K.S,M,GEN,42,IND,378,26
8068,U07,Puducherry,3,2009,1,Puducherry,GEN,I.M. SEKAR,M,GEN,46,IND,375,27
8069,U07,Puducherry,3,2009,1,Puducherry,GEN,MOHAMED YOUSUF. S.A,M,GEN,46,IND,298,28

In [38]:
 age = cw.pivot_table(values=['Candidate Age'],index=['State name'],columns=['Candidate Sex'], aggfunc=len)

In [39]:
age

                          Candidate Age
Candidate Sex                         F       M
State name
Andaman & Nicobar Islands           1.0    10.0
Andhra Pradesh                     39.0   530.0
Arunachal Pradesh                   NaN     8.0
Assam                              11.0   147.0
Bihar                              46.0   626.0
Chandigarh                          1.0    13.0
Chattisgarh                        15.0   163.0
Dadra & Nagar Haveli                NaN     5.0
Daman & Diu                         NaN     7.0
Goa                                 2.0    16.0
Gujarat                            26.0   333.0
Haryana                            14.0   196.0
Himachal Pradesh                    1.0    30.0
Jammu & Kashmir                     6.0    75.0
Jharkhand                          14.0   235.0
Karnataka                          19.0   408.0
Kerala                             15.0   202.0
Lakshadweep                         NaN     4.0
Madhya Pradesh                     29.0   400.0
Maharashtra                        55.0   764.0
Manipur                             3.0    13.0
Meghalaya                           3.0     8.0
Mizoram                             NaN     4.0
NCT OF Delhi                       18.0   142.0
Nagaland                            NaN     3.0
Orissa                              9.0   148.0
Puducherry                          NaN    28.0
Punjab                             13.0   205.0
Rajasthan                          31.0   315.0
Sikkim                              NaN     7.0
Tamil Nadu                         48.0   775.0
Tripura                             1.0    18.0
Uttar Pradesh                     100.0  1268.0
Uttarakhand                         7.0    69.0
West Bengal                        29.0   339.0

In [40]:
a=age['Candidate Age','F']
b=age['Candidate Age','M']

In [41]:
def gcd(a,b):
    if b>a:
        while b > 0:
            a, b = b, a % b
        return a
    elif a>b:
        while a > 0:
            b, a = a, b % a
        return b
    else:
        return 1

In [42]:
age.reset_index(inplace=True)

In [43]:
age.fillna(value=0)

                              State name Candidate Age
Candidate Sex                                        F       M
0              Andaman & Nicobar Islands           1.0    10.0
1                         Andhra Pradesh          39.0   530.0
2                      Arunachal Pradesh           0.0     8.0
3                                  Assam          11.0   147.0
4                                  Bihar          46.0   626.0
5                             Chandigarh           1.0    13.0
6                            Chattisgarh          15.0   163.0
7                   Dadra & Nagar Haveli           0.0     5.0
8                            Daman & Diu           0.0     7.0
9                                    Goa           2.0    16.0
10                               Gujarat          26.0   333.0
11                               Haryana          14.0   196.0
12                      Himachal Pradesh           1.0    30.0
13                       Jammu & Kashmir           6.0    75.0
14                             Jharkhand          14.0   235.0
15                             Karnataka          19.0   408.0
16                                Kerala          15.0   202.0
17                           Lakshadweep           0.0     4.0
18                        Madhya Pradesh          29.0   400.0
19                           Maharashtra          55.0   764.0
20                               Manipur           3.0    13.0
21                             Meghalaya           3.0     8.0
22                               Mizoram           0.0     4.0
23                          NCT OF Delhi          18.0   142.0
24                              Nagaland           0.0     3.0
25                                Orissa           9.0   148.0
26                            Puducherry           0.0    28.0
27                                Punjab          13.0   205.0
28                             Rajasthan          31.0   315.0
29                                Sikkim           0.0     7.0
30                            Tamil Nadu          48.0   775.0
31                               Tripura           1.0    18.0
32                         Uttar Pradesh         100.0  1268.0
33                           Uttarakhand           7.0    69.0
34                           West Bengal          29.0   339.0

In [44]:
x = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in age.index:
    x[i] = gcd(a[i],b[i])

In [46]:
f=a/x.copy()
m=b/x.copy()

In [47]:
f=pd.Series.to_frame(f)

In [48]:
f.reset_index(inplace=True)

In [49]:
m=pd.Series.to_frame(m)

In [50]:
m.reset_index(inplace=True)

In [53]:
m.columns = m.columns.get_level_values(1)

In [55]:
ck = list(m.columns)

In [58]:
ck[0]='STATE'
ck[1]='Male_Candidates'

In [59]:
m.columns= ck

In [61]:
f.columns = f.columns.get_level_values(1)

In [62]:
cl = list(f.columns)

In [63]:
cl[0]='STATE'
cl[1]='Female_Candidates'

In [64]:
f.columns= cl

In [68]:
age.columns = age.columns.get_level_values(1)

In [69]:
ca = list(age.columns)

In [70]:
ca

['', 'F', 'M']

In [71]:
ca[0]='STATE'

In [72]:
age.columns = ca

In [73]:
age

                        STATE      F       M
0   Andaman & Nicobar Islands    1.0    10.0
1              Andhra Pradesh   39.0   530.0
2           Arunachal Pradesh    NaN     8.0
3                       Assam   11.0   147.0
4                       Bihar   46.0   626.0
5                  Chandigarh    1.0    13.0
6                 Chattisgarh   15.0   163.0
7        Dadra & Nagar Haveli    NaN     5.0
8                 Daman & Diu    NaN     7.0
9                         Goa    2.0    16.0
10                    Gujarat   26.0   333.0
11                    Haryana   14.0   196.0
12           Himachal Pradesh    1.0    30.0
13            Jammu & Kashmir    6.0    75.0
14                  Jharkhand   14.0   235.0
15                  Karnataka   19.0   408.0
16                     Kerala   15.0   202.0
17                Lakshadweep    NaN     4.0
18             Madhya Pradesh   29.0   400.0
19                Maharashtra   55.0   764.0
20                    Manipur    3.0    13.0
21                  Meghalaya    3.0     8.0
22                    Mizoram    NaN     4.0
23               NCT OF Delhi   18.0   142.0
24                   Nagaland    NaN     3.0
25                     Orissa    9.0   148.0
26                 Puducherry    NaN    28.0
27                     Punjab   13.0   205.0
28                  Rajasthan   31.0   315.0
29                     Sikkim    NaN     7.0
30                 Tamil Nadu   48.0   775.0
31                    Tripura    1.0    18.0
32              Uttar Pradesh  100.0  1268.0
33                Uttarakhand    7.0    69.0
34                West Bengal   29.0   339.0

In [74]:
o=pd.merge(age,f,on='STATE')

In [75]:
oge=pd.merge(o,m,on='STATE')

In [77]:
oge.fillna(value=0,inplace=True)

In [78]:
oge

,STATE,F,M,Female_Candidates,Male_Candidates
0,Andaman & Nicobar Islands,1.0,10.0,1.0,10.0
1,Andhra Pradesh,39.0,530.0,39.0,530.0
2,Arunachal Pradesh,0.0,8.0,0.0,8.0
3,Assam,11.0,147.0,11.0,147.0
4,Bihar,46.0,626.0,23.0,313.0
5,Chandigarh,1.0,13.0,1.0,13.0
6,Chattisgarh,15.0,163.0,15.0,163.0
7,Dadra & Nagar Haveli,0.0,5.0,0.0,5.0
8,Daman & Diu,0.0,7.0,0.0,7.0
9,Goa,2.0,16.0,1.0,8.0
10,Gujarat,26.0,333.0,26.0,333.0
11,Haryana,14.0,196.0,1.0,14.0
12,Himachal Pradesh,1.0,30.0,1.0,30.0
13,Jammu & Kashmir,6.0,75.0,2.0,25.0
14,Jharkhand,14.0,235.0,14.0,235.0
15,Karnataka,19.0,408.0,19.0,408.0
16,Kerala,15.0,202.0,15.0,202.0
17,Lakshadweep,0.0,4.0,0.0,4.0
18,Madhya Pradesh,29.0,400.0,29.0,400.0
19,Maharashtra,55.0,764.0,55.0,764.0
20,Manipur,3.0,13.0,3.0,13.0
21,Meghalaya,3.0,8.0,3.0,8.0
22,Mizoram,0.0,4.0,0.0,4.0
23,NCT OF Delhi,18.0,142.0,9.0,71.0
24,Nagaland,0.0,3.0,0.0,3.0
25,Orissa,9.0,148.0,9.0,148.0
26,Puducherry,0.0,28.0,0.0,28.0
27,Punjab,13.0,205.0,13.0,205.0
28,Rajasthan,31.0,315.0,31.0,315.0
29,Sikkim,0.0,7.0,0.0,7.0
30,Tamil Nadu,48.0,775.0,48.0,775.0
31,Tripura,1.0,18.0,1.0,18.0
32,Uttar Pradesh,100.0,1268.0,25.0,317.0
33,Uttarakhand,7.0,69.0,7.0,69.0
34,West Bengal,29.0,339.0,29.0,339.0

In [79]:
oge['FtoM_ratio'] = oge['Female_Candidates'].astype(str).str.cat(oge['Male_Candidates'].astype(str), sep=' : ')

In [80]:
oge

,STATE,F,M,Female_Candidates,Male_Candidates,FtoM_ratio
0,Andaman & Nicobar Islands,1.0,10.0,1.0,10.0,1.0 : 10.0
1,Andhra Pradesh,39.0,530.0,39.0,530.0,39.0 : 530.0
2,Arunachal Pradesh,0.0,8.0,0.0,8.0,0.0 : 8.0
3,Assam,11.0,147.0,11.0,147.0,11.0 : 147.0
4,Bihar,46.0,626.0,23.0,313.0,23.0 : 313.0
5,Chandigarh,1.0,13.0,1.0,13.0,1.0 : 13.0
6,Chattisgarh,15.0,163.0,15.0,163.0,15.0 : 163.0
7,Dadra & Nagar Haveli,0.0,5.0,0.0,5.0,0.0 : 5.0
8,Daman & Diu,0.0,7.0,0.0,7.0,0.0 : 7.0
9,Goa,2.0,16.0,1.0,8.0,1.0 : 8.0
10,Gujarat,26.0,333.0,26.0,333.0,26.0 : 333.0
11,Haryana,14.0,196.0,1.0,14.0,1.0 : 14.0
12,Himachal Pradesh,1.0,30.0,1.0,30.0,1.0 : 30.0
13,Jammu & Kashmir,6.0,75.0,2.0,25.0,2.0 : 25.0
14,Jharkhand,14.0,235.0,14.0,235.0,14.0 : 235.0
15,Karnataka,19.0,408.0,19.0,408.0,19.0 : 408.0
16,Kerala,15.0,202.0,15.0,202.0,15.0 : 202.0
17,Lakshadweep,0.0,4.0,0.0,4.0,0.0 : 4.0
18,Madhya Pradesh,29.0,400.0,29.0,400.0,29.0 : 400.0
19,Maharashtra,55.0,764.0,55.0,764.0,55.0 : 764.0
20,Manipur,3.0,13.0,3.0,13.0,3.0 : 13.0
21,Meghalaya,3.0,8.0,3.0,8.0,3.0 : 8.0
22,Mizoram,0.0,4.0,0.0,4.0,0.0 : 4.0
23,NCT OF Delhi,18.0,142.0,9.0,71.0,9.0 : 71.0
24,Nagaland,0.0,3.0,0.0,3.0,0.0 : 3.0
25,Orissa,9.0,148.0,9.0,148.0,9.0 : 148.0
26,Puducherry,0.0,28.0,0.0,28.0,0.0 : 28.0
27,Punjab,13.0,205.0,13.0,205.0,13.0 : 205.0
28,Rajasthan,31.0,315.0,31.0,315.0,31.0 : 315.0
29,Sikkim,0.0,7.0,0.0,7.0,0.0 : 7.0
30,Tamil Nadu,48.0,775.0,48.0,775.0,48.0 : 775.0
31,Tripura,1.0,18.0,1.0,18.0,1.0 : 18.0
32,Uttar Pradesh,100.0,1268.0,25.0,317.0,25.0 : 317.0
33,Uttarakhand,7.0,69.0,7.0,69.0,7.0 : 69.0
34,West Bengal,29.0,339.0,29.0,339.0,29.0 : 339.0

In [81]:
del oge['Female_Candidates']

In [82]:
del oge['Male_Candidates']

In [83]:
oge

                        STATE      F       M    FtoM_ratio
0   Andaman & Nicobar Islands    1.0    10.0    1.0 : 10.0
1              Andhra Pradesh   39.0   530.0  39.0 : 530.0
2           Arunachal Pradesh    0.0     8.0     0.0 : 8.0
3                       Assam   11.0   147.0  11.0 : 147.0
4                       Bihar   46.0   626.0  23.0 : 313.0
5                  Chandigarh    1.0    13.0    1.0 : 13.0
6                 Chattisgarh   15.0   163.0  15.0 : 163.0
7        Dadra & Nagar Haveli    0.0     5.0     0.0 : 5.0
8                 Daman & Diu    0.0     7.0     0.0 : 7.0
9                         Goa    2.0    16.0     1.0 : 8.0
10                    Gujarat   26.0   333.0  26.0 : 333.0
11                    Haryana   14.0   196.0    1.0 : 14.0
12           Himachal Pradesh    1.0    30.0    1.0 : 30.0
13            Jammu & Kashmir    6.0    75.0    2.0 : 25.0
14                  Jharkhand   14.0   235.0  14.0 : 235.0
15                  Karnataka   19.0   408.0  19.0 : 408.0
16                     Kerala   15.0   202.0  15.0 : 202.0
17                Lakshadweep    0.0     4.0     0.0 : 4.0
18             Madhya Pradesh   29.0   400.0  29.0 : 400.0
19                Maharashtra   55.0   764.0  55.0 : 764.0
20                    Manipur    3.0    13.0    3.0 : 13.0
21                  Meghalaya    3.0     8.0     3.0 : 8.0
22                    Mizoram    0.0     4.0     0.0 : 4.0
23               NCT OF Delhi   18.0   142.0    9.0 : 71.0
24                   Nagaland    0.0     3.0     0.0 : 3.0
25                     Orissa    9.0   148.0   9.0 : 148.0
26                 Puducherry    0.0    28.0    0.0 : 28.0
27                     Punjab   13.0   205.0  13.0 : 205.0
28                  Rajasthan   31.0   315.0  31.0 : 315.0
29                     Sikkim    0.0     7.0     0.0 : 7.0
30                 Tamil Nadu   48.0   775.0  48.0 : 775.0
31                    Tripura    1.0    18.0    1.0 : 18.0
32              Uttar Pradesh  100.0  1268.0  25.0 : 317.0
33                Uttarakhand    7.0    69.0    7.0 : 69.0
34                West Bengal   29.0   339.0  29.0 : 339.0

In [87]:
s2009.to_csv('s2009.csv',index=False)

In [89]:
s2009.reset_index(inplace=True)

In [90]:
s2009

2,STATE,TOT_CONTESTANT,Total voters,Total_Electors,POLL_PERC in %
0,Andaman & Nicobar Islands,11,170103,265108,64.163662
1,Andhra Pradesh,569,42083881,57892259,72.693451
2,Arunachal Pradesh,8,500649,734541,68.158074
3,Assam,158,12148928,17470329,69.540350
4,Bihar,672,24236704,54505246,44.466736
5,Chandigarh,14,343558,524444,65.508996
6,Chattisgarh,178,8556920,15476577,55.289487
7,Dadra & Nagar Haveli,5,110363,150704,73.231633
8,Daman & Diu,7,68025,95382,71.318488
9,Goa,18,564439,1020794,55.294114
10,Gujarat,359,17476567,36484281,47.901635
11,Haryana,210,8160347,12087710,67.509454
12,Himachal Pradesh,31,2691573,4606674,58.427686
13,Jammu & Kashmir,81,2609249,6572896,39.697099
14,Jharkhand,249,9142643,17934095,50.979115
15,Karnataka,427,24581348,41790939,58.819803
16,Kerala,217,16041499,21859536,73.384444
17,Lakshadweep,4,39498,45983,85.896962
18,Madhya Pradesh,429,19488631,38085179,51.171168
19,Maharashtra,819,37007318,72954058,50.726881
20,Manipur,16,1342309,1736251,77.310769
21,Meghalaya,11,822614,1277739,64.380441
22,Mizoram,4,326424,629374,51.864869
23,NCT OF Delhi,160,5754353,11096854,51.855715
24,Nagaland,3,1189742,1321878,90.003919
25,Orissa,157,17772023,27194864,65.350660
26,Puducherry,28,608509,762440,79.810739
27,Punjab,218,11833883,16958380,69.781919
28,Rajasthan,346,17942008,37060011,48.413391
29,Sikkim,7,252274,300584,83.927954
30,Tamil Nadu,823,30404136,41620460,73.050937
31,Tripura,19,1760485,2082265,84.546636
32,Uttar Pradesh,1368,55434443,116006374,47.785687
33,Uttarakhand,76,3145818,5887724,53.430120
34,West Bengal,368,42740385,52493168,81.420853

In [91]:
output = pd.merge(s2009,oge,on='STATE')

In [92]:
output

,STATE,TOT_CONTESTANT,Total voters,Total_Electors,POLL_PERC in %,F,M,FtoM_ratio
0,Andaman & Nicobar Islands,11,170103,265108,64.163662,1.0,10.0,1.0 : 10.0
1,Andhra Pradesh,569,42083881,57892259,72.693451,39.0,530.0,39.0 : 530.0
2,Arunachal Pradesh,8,500649,734541,68.158074,0.0,8.0,0.0 : 8.0
3,Assam,158,12148928,17470329,69.540350,11.0,147.0,11.0 : 147.0
4,Bihar,672,24236704,54505246,44.466736,46.0,626.0,23.0 : 313.0
5,Chandigarh,14,343558,524444,65.508996,1.0,13.0,1.0 : 13.0
6,Chattisgarh,178,8556920,15476577,55.289487,15.0,163.0,15.0 : 163.0
7,Dadra & Nagar Haveli,5,110363,150704,73.231633,0.0,5.0,0.0 : 5.0
8,Daman & Diu,7,68025,95382,71.318488,0.0,7.0,0.0 : 7.0
9,Goa,18,564439,1020794,55.294114,2.0,16.0,1.0 : 8.0
10,Gujarat,359,17476567,36484281,47.901635,26.0,333.0,26.0 : 333.0
11,Haryana,210,8160347,12087710,67.509454,14.0,196.0,1.0 : 14.0
12,Himachal Pradesh,31,2691573,4606674,58.427686,1.0,30.0,1.0 : 30.0
13,Jammu & Kashmir,81,2609249,6572896,39.697099,6.0,75.0,2.0 : 25.0
14,Jharkhand,249,9142643,17934095,50.979115,14.0,235.0,14.0 : 235.0
15,Karnataka,427,24581348,41790939,58.819803,19.0,408.0,19.0 : 408.0
16,Kerala,217,16041499,21859536,73.384444,15.0,202.0,15.0 : 202.0
17,Lakshadweep,4,39498,45983,85.896962,0.0,4.0,0.0 : 4.0
18,Madhya Pradesh,429,19488631,38085179,51.171168,29.0,400.0,29.0 : 400.0
19,Maharashtra,819,37007318,72954058,50.726881,55.0,764.0,55.0 : 764.0
20,Manipur,16,1342309,1736251,77.310769,3.0,13.0,3.0 : 13.0
21,Meghalaya,11,822614,1277739,64.380441,3.0,8.0,3.0 : 8.0
22,Mizoram,4,326424,629374,51.864869,0.0,4.0,0.0 : 4.0
23,NCT OF Delhi,160,5754353,11096854,51.855715,18.0,142.0,9.0 : 71.0
24,Nagaland,3,1189742,1321878,90.003919,0.0,3.0,0.0 : 3.0
25,Orissa,157,17772023,27194864,65.350660,9.0,148.0,9.0 : 148.0
26,Puducherry,28,608509,762440,79.810739,0.0,28.0,0.0 : 28.0
27,Punjab,218,11833883,16958380,69.781919,13.0,205.0,13.0 : 205.0
28,Rajasthan,346,17942008,37060011,48.413391,31.0,315.0,31.0 : 315.0
29,Sikkim,7,252274,300584,83.927954,0.0,7.0,0.0 : 7.0
30,Tamil Nadu,823,30404136,41620460,73.050937,48.0,775.0,48.0 : 775.0
31,Tripura,19,1760485,2082265,84.546636,1.0,18.0,1.0 : 18.0
32,Uttar Pradesh,1368,55434443,116006374,47.785687,100.0,1268.0,25.0 : 317.0
33,Uttarakhand,76,3145818,5887724,53.430120,7.0,69.0,7.0 : 69.0
34,West Bengal,368,42740385,52493168,81.420853,29.0,339.0,29.0 : 339.0

In [93]:
output.to_csv('GE2009_detail.csv',index=False)

In [95]:
g=cw[cw['Position']==1].copy()

In [98]:
pp=g.pivot_table(index=['State name','Party Abbreviation'],values='Total Votes Polled', aggfunc=len).copy()

In [99]:
g['Candidate Sex'].value_counts()

M    485
F     58
Name: Candidate Sex, dtype: int64

In [100]:
qw = pd.DataFrame(g['Candidate Sex'].value_counts())

In [103]:
qw.reset_index(inplace=True)

In [104]:
qw

  index  Candidate Sex
0     M            485
1     F             58

In [115]:
qw.rename(columns={'index':'Indicators','Election 1999':'Election 2009'},inplace=True)

In [116]:
qw

  Indicators  Election 2009
0          M            485
1          F             58

In [163]:
qw['Indicators'][0]= 'Male in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [164]:
qw['Indicators'][1]= 'Female in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [137]:
ind = pd.DataFrame(g['Party Abbreviation'].describe())

In [138]:
ind

       Party Abbreviation
count                 543
unique                 38
top                   INC
freq                  206

In [139]:
ind.reset_index(inplace=True)

In [140]:
ind.rename(columns={'index':'Indicators','Party Abbreviation':'Election 2009'},inplace=True)

In [141]:
ind

  Indicators Election 2009
0      count           543
1     unique            38
2        top           INC
3       freq           206

In [154]:
ind['Indicators'][0]= 'Total seats contested for'

In [155]:
ind['Indicators'][1]= 'Number of Parties'

In [156]:
ind['Indicators'][2]= 'Party with majority'

In [157]:
ind['Indicators'][3]= 'Majority party eats won'

In [158]:
eld = pd.read_csv('ecyw.csv')

In [159]:
todisplay=eld[['Indicators','Election 2009']].copy()

In [160]:
todisplay

                                          Indicators  Election 2009
0   India's Real GDP Growth Rates\r\r\n(Factor Cost)          6.680
1                             Agriculture growth (%)          4.112
2                                Industry growth (%)          5.166
3                                Services growth (%)          8.096
4                                   By Demand (%YoY)            NaN
5                                        Consumption          7.080
6                                Private Consumption          7.040
7                                 Public Consumption          7.320
8                      Gross Fixed Capital Formation          6.340
9           Consumption; Investments, Savings (%GDP)            NaN
10                                       Consumption         68.560
11                                 Capital Formation         35.060
12                            Gross Domestic Savings         31.862
13                                      Money Supply         16.320
14                                Bank Credit growth         16.900
15                                    Deposit growth         14.860
16                         Fiscal Indicators (% GDP)            NaN
17                           Centre's Fiscal Deficit         -5.300
18                              State Fiscal Deficit         -2.380
19                   Combined Deficit (Centre+State)         -7.700
20                         Inflation - WPI (Average)          7.080
21                                     CPI (Average)         10.180
22                                   Exports (US$bn)        273.580
23                                             % YoY         12.080
24                                   Imports (US$bn)        429.920
25                                              %YoY          9.732
26                             Trade deficit (US$bn)       -156.380
27                                Invisibles (US$bn)         99.780
28                   Current Account Deficit (US$bn)        -56.580
29                                          % to GDP         -3.220
30                           Capital Account (US$bn)         63.900
31                                             % GDP          3.680
32                   Forex Assets (exc. gold)(US$bn)        298.000
33                             External Debt (US$bn)        358.240
34                                   Short Term Debt         76.280
35                       Exchange Rate US$/Rs. -avg.         51.100

In [168]:
col1=pd.concat([todisplay,qw,ind]).reset_index()

In [169]:
del col1['index']

In [170]:
col1

                                          Indicators Election 2009
0   India's Real GDP Growth Rates\r\r\n(Factor Cost)          6.68
1                             Agriculture growth (%)         4.112
2                                Industry growth (%)         5.166
3                                Services growth (%)         8.096
4                                   By Demand (%YoY)           NaN
5                                        Consumption          7.08
6                                Private Consumption          7.04
7                                 Public Consumption          7.32
8                      Gross Fixed Capital Formation          6.34
9           Consumption; Investments, Savings (%GDP)           NaN
10                                       Consumption         68.56
11                                 Capital Formation         35.06
12                            Gross Domestic Savings        31.862
13                                      Money Supply         16.32
14                                Bank Credit growth          16.9
15                                    Deposit growth         14.86
16                         Fiscal Indicators (% GDP)           NaN
17                           Centre's Fiscal Deficit          -5.3
18                              State Fiscal Deficit         -2.38
19                   Combined Deficit (Centre+State)          -7.7
20                         Inflation - WPI (Average)          7.08
21                                     CPI (Average)         10.18
22                                   Exports (US$bn)        273.58
23                                             % YoY         12.08
24                                   Imports (US$bn)        429.92
25                                              %YoY         9.732
26                             Trade deficit (US$bn)       -156.38
27                                Invisibles (US$bn)         99.78
28                   Current Account Deficit (US$bn)        -56.58
29                                          % to GDP         -3.22
30                           Capital Account (US$bn)          63.9
31                                             % GDP          3.68
32                   Forex Assets (exc. gold)(US$bn)           298
33                             External Debt (US$bn)        358.24
34                                   Short Term Debt         76.28
35                       Exchange Rate US$/Rs. -avg.          51.1
36                                Male in LowerHouse           485
37                              Female in LowerHouse            58
38                         Total seats contested for           543
39                                 Number of Parties            38
40                               Party with majority           INC
41                           Majority party eats won           206

In [171]:
col1.to_csv('dt2009.csv',index=False)