In [1]:
import pandas as pd
import numpy as np
import plotly as py
import seaborn as sb
%matplotlib inline
import xlrd

In [2]:
ge2014 = pd.ExcelFile('GE_2014.xls')

In [3]:
ge14el = ge2014.parse('electors')

In [4]:
ge14el.columns = ge14el.iloc[2]
ge14el.reindex(ge14el.index.drop(2))

2,STATE CODE,STATE,PC NO,PARLIAMENTARY CONSTITUENCY,Total voters,Total_Electors,POLL PERCENTAGE
0,GENERAL ELECTION 2014,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S01,Andhra Pradesh,1,Adilabad,1055593,1386282,76.15
4,S01,Andhra Pradesh,2,Peddapalle,1025194,1425355,71.93
5,S01,Andhra Pradesh,3,Karimnagar,1127225,1550810,72.69
6,S01,Andhra Pradesh,4,Nizamabad,1034032,1496193,69.11
7,S01,Andhra Pradesh,5,Zahirabad,1099784,1445354,76.09
8,S01,Andhra Pradesh,6,Medak,1193548,1536166,77.7
9,S01,Andhra Pradesh,7,Malkajgiri,1624859,3183083,51.05
10,S01,Andhra Pradesh,8,Secundrabad,1004763,1893741,53.06
11,S01,Andhra Pradesh,9,Hyderabad,971770,1823217,53.3
12,S01,Andhra Pradesh,10,CHELVELLA,1322312,2185164,60.51
13,S01,Andhra Pradesh,11,Mahbubnagar,1015520,1418668,71.58
14,S01,Andhra Pradesh,12,Nagarkurnool,1116159,1477305,75.55
15,S01,Andhra Pradesh,13,Nalgonda,1191667,1494343,79.75
16,S01,Andhra Pradesh,14,Bhongir,1212738,1492240,81.27
17,S01,Andhra Pradesh,15,Warangal,1176653,1537778,76.52
18,S01,Andhra Pradesh,16,Mahabubabad,1126618,1387288,81.21
19,S01,Andhra Pradesh,17,Khammam,1188875,1440267,82.55
20,S01,Andhra Pradesh,18,Aruku,913838,1272340,71.82
21,S01,Andhra Pradesh,19,Srikakulam,1054640,1413726,74.6
22,S01,Andhra Pradesh,20,Vizianagaram,1125615,1403736,80.19
23,S01,Andhra Pradesh,21,Visakhapatnam,1163582,1723011,67.53
24,S01,Andhra Pradesh,22,Anakapalli,1149326,1401474,82.01
25,S01,Andhra Pradesh,23,Kakinada,1101730,1418290,77.68
26,S01,Andhra Pradesh,24,Amalapuram,1121986,1357865,82.63
27,S01,Andhra Pradesh,25,Rajahmundry,1156626,1421276,81.38
28,S01,Andhra Pradesh,26,Narsapuram,1089102,1325028,82.19
29,S01,Andhra Pradesh,27,Eluru,1203236,1427764,84.27
30,S01,Andhra Pradesh,28,Machilipatnam,1143048,1369311,83.48
...,...,...,...,...,...,...,...
516,S27,Jharkhand,3,Godda,1049642,1590772,65.98
517,S27,Jharkhand,4,Chatra,712980,1312562,54.32
518,S27,Jharkhand,5,Kodarma,1024939,1639645,62.51
519,S27,Jharkhand,6,Giridih,971242,1511644,64.25
520,S27,Jharkhand,7,Dhanbad,1143945,1890021,60.53
521,S27,Jharkhand,8,Ranchi,1049787,1648459,63.68
522,S27,Jharkhand,9,Jamshedpur,1049164,1581665,66.33
523,S27,Jharkhand,10,Singhbhum,795352,1152632,69
524,S27,Jharkhand,11,Khunti,737611,1111856,66.34
525,S27,Jharkhand,12,Lohardaga,651639,1119144,58.23
526,S27,Jharkhand,13,Palamau,978159,1645957,59.43
527,S27,Jharkhand,14,Hazaribagh,967348,1518923,63.69
528,S28,Uttarakhand,1,Tehri Garhwal,776945,1352614,57.44
529,S28,Uttarakhand,2,Garhwal,684014,1267218,53.98
530,S28,Uttarakhand,3,Almora,656934,1253541,52.41
531,S28,Uttarakhand,4,Nainital-udhamsingh Nagar,1101934,1610811,68.41
532,S28,Uttarakhand,5,Hardwar,1175734,1642873,71.57
533,U01,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,190346,269360,70.67
534,U02,Chandigarh,1,CHANDIGARH,453462,615214,73.71
535,U03,Dadra & Nagar Haveli,1,Dadar & Nagar Haveli,165324,196597,84.09
536,U04,Daman & Diu,1,Daman & diu,87233,111827,78.01
537,U05,NCT OF Delhi,1,CHANDNI CHOWK,982275,1447230,67.87
538,U05,NCT OF Delhi,2,NORTH EAST DELHI,1317974,1957708,67.32
539,U05,NCT OF Delhi,3,EAST DELHI,1196731,1829578,65.41
540,U05,NCT OF Delhi,4,NEW DELHI,970169,1490147,65.11
541,U05,NCT OF Delhi,5,NORTH WEST DELHI,1356404,2194343,61.81
542,U05,NCT OF Delhi,6,WEST DELHI,1348744,2039410,66.13
543,U05,NCT OF Delhi,7,SOUTH DELHI,1102849,1752748,62.92
544,U06,Lakshadweep,1,Lakshadweep,43242,49922,86.62
545,U07,Puducherry,1,Puducherry,740053,901357,82.1

In [5]:
ge14el.drop(0, inplace = True)
ge14el.drop(1, inplace = True)
ge14el.drop(2, inplace = True)
ge14el.reset_index(inplace=True)

In [6]:
del ge14el['index']

In [7]:
ge14el.columns

Index(['STATE CODE', 'STATE', 'PC NO', 'PARLIAMENTARY CONSTITUENCY',
       'Total voters', 'Total_Electors', 'POLL PERCENTAGE'],
      dtype='object', name=2)

In [8]:
s2014 = pd.pivot_table(ge14el,index='STATE',values=['Total voters', 'Total_Electors'],aggfunc=sum)

In [9]:
s2014['POLL_PERC in %']=(s2014['Total voters']/s2014['Total_Electors']*100)

In [10]:
s2014

2                          Total voters  Total_Electors  POLL_PERC in %
STATE
Andaman & Nicobar Islands        190346          269360       70.666023
Andhra Pradesh                 48467721        64934138       74.641356
Arunachal Pradesh                600828          759344       79.124613
Assam                          15092387        18837713       80.117937
Bihar                          35892459        63800160       56.257632
Chandigarh                       453462          615214       73.708011
Chhattisgarh                   12256962        17664520       69.387461
Dadra & Nagar Haveli             165324          196597       84.092840
Daman & Diu                       87233          111827       78.007100
Goa                              817440         1060777       77.060494
Gujarat                        25849655        40603104       63.664234
Haryana                        11501251        16097233       71.448621
Himachal Pradesh                3100199         4810071       64.452250
Jammu & Kashmir                 3571537         7183129       49.721187
Jharkhand                      12986625        20349796       63.816979
Karnataka                      31053583        46209813       67.201274
Kerala                         17987124        24326650       73.939996
Lakshadweep                       43242           49922       86.619126
Madhya Pradesh                 29648105        48121301       61.611188
Maharashtra                    48740403        80798823       60.323160
Manipur                         1415131         1774369       79.754042
Meghalaya                       1078295         1567241       68.802118
Mizoram                          434962          702170       61.945398
NCT OF Delhi                    8275146        12711164       65.101402
Nagaland                        1039962         1182972       87.910956
Odisha                         21542724        29196045       73.786446
Puducherry                       740053          901357       82.104316
Punjab                         13849496        19608161       70.631285
Rajasthan                      27133776        42994657       63.109646
Sikkim                           310095          370770       83.635407
Tamil Nadu                     40644282        55114867       73.744679
Tripura                         2028707         2388822       84.924997
Uttar Pradesh                  81118615       138810557       58.438361
Uttarakhand                     4395561         7127057       61.674279
West Bengal                    51662564        62833113       82.221876

In [11]:
ge14cw = ge2014.parse('Cand_Wise')

In [12]:
ge14cw.columns = ge14cw.iloc[2]
ge14cw.reindex(ge14cw.index.drop(2))

2,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,GENERAL ELECTION 2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,GODAM NAGESH,M,ST,49,TRS,430847,1
4,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NARESH,M,ST,37,INC,259557,2
5,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RAMESH RATHOD,M,ST,48,TDP,184198,3
6,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RATHOD SADASHIV,M,ST,55,BSP,94420,4
7,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NETHAWATH RAMDAS,M,ST,44,IND,41032,5
8,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,None of the Above,NaN,NaN,NaN,NOTA,17084,6
9,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,MOSALI CHINNAIAH,M,ST,40,IND,8859,7
10,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,PAWAR KRISHNA,M,ST,33,IND,5055,8
11,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,BANKA SAHADEV,M,ST,53,IND,4787,9
12,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BALKA SUMAN,M,SC,31,TRS,565496,1
13,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,G. VIVEKANAND,M,SC,56,INC,274338,2
14,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,DR.JANAPATI SARAT BABU,M,SC,42,TDP,63334,3
15,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VELTHURU MALLAIAH,M,SC,57,RP(K),45977,4
16,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,TAGARAM SHANKAR LAL,M,SC,37,BSP,9449,5
17,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SHANKAR,M,SC,44,PPOI,9290,6
18,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,JINNA RAMADEVI,F,SC,37,IND,9199,7
19,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SANJEEV,M,SC,37,RPI,8609,8
20,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BUPELLI NARAYANA,M,SC,30,IND,7258,9
21,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,None of the Above,NaN,NaN,NaN,NOTA,5361,10
22,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VENKATA SWAMY INJAM,M,SC,42,MaSP,3866,11
23,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,THALLAPALLI SRINIVAS,M,SC,35,IND,3699,12
24,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GADDALA VINAY KUMAR,M,SC,65,IND,3266,13
25,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,J.V. RAJU,M,SC,50,NIP,3020,14
26,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KAMILLA JAYA RAO,M,SC,43,IND,2742,15
27,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,MOUTAM RAVINDER,M,SC,33,IND,2674,16
28,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GORRE RAMESH,M,SC,43,IND,2361,17
29,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BOTHA VENKATA MALLAIAH,M,SC,58,BCUF,2245,18
30,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,54,TRS,505358,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8767,U07,Puducherry,5,2014,1,Puducherry,GEN,V. NARAYANASAMY,M,GEN,66,INC,194972,2
8768,U07,Puducherry,5,2014,1,Puducherry,GEN,M.V. OMALINGAM,M,GEN,42,ADMK,132657,3
8769,U07,Puducherry,5,2014,1,Puducherry,GEN,A.M.H. NAZEEM,M,GEN,52,DMK,60580,4
8770,U07,Puducherry,5,2014,1,Puducherry,GEN,R.K.R. ANANTHARAMAN,M,GEN,41,PMK,22754,5
8771,U07,Puducherry,5,2014,1,Puducherry,GEN,None of the Above,NaN,NaN,NaN,NOTA,22268,6
8772,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VISWANATHAN,M,GEN,64,CPI,12709,7
8773,U07,Puducherry,5,2014,1,Puducherry,GEN,DR. V. RANGARAJAN,M,GEN,59,AAAP,8307,8
8774,U07,Puducherry,5,2014,1,Puducherry,GEN,SANJIVGANTHI .S,M,SC,30,IND,5896,9
8775,U07,Puducherry,5,2014,1,Puducherry,GEN,P. ASARAVEL,M,SC,41,IND,3472,10
8776,U07,Puducherry,5,2014,1,Puducherry,GEN,PROFESSOR M. RAMADASS,M,GEN,64,IND,2494,11
8777,U07,Puducherry,5,2014,1,Puducherry,GEN,S. KRISHNAMOORTHY,M,SC,48,BSP,2060,12
8778,U07,Puducherry,5,2014,1,Puducherry,GEN,S. EZHILARASAN,M,SC,41,IND,1777,13
8779,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SHANMUGAM,M,GEN,50,IND,1726,14
8780,U07,Puducherry,5,2014,1,Puducherry,GEN,RAMAMURTHI,M,GEN,53,IND,1442,15
8781,U07,Puducherry,5,2014,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,37,IND,1340,16
8782,U07,Puducherry,5,2014,1,Puducherry,GEN,S. SUDARSANAN,M,GEN,37,IND,1270,17
8783,U07,Puducherry,5,2014,1,Puducherry,GEN,K. RAMADASS,M,SC,49,IND,1236,18
8784,U07,Puducherry,5,2014,1,Puducherry,GEN,J. DHANDAPANI,M,GEN,61,IND,1144,19
8785,U07,Puducherry,5,2014,1,Puducherry,GEN,K. MANJINI,M,GEN,41,IND,767,20
8786,U07,Puducherry,5,2014,1,Puducherry,GEN,KALIAYAMURTHY,M,SC,44,IND,747,21
8787,U07,Puducherry,5,2014,1,Puducherry,GEN,V. VIJAYA,F,GEN,29,IND,746,22
8788,U07,Puducherry,5,2014,1,Puducherry,GEN,P. BAKKIARAJ,M,SC,31,IND,610,23
8789,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VALAVAN,M,GEN,40,IND,497,24
8790,U07,Puducherry,5,2014,1,Puducherry,GEN,I. SENTHIL KUMAR,M,GEN,31,IND,477,25
8791,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SUTHA,F,SC,30,IND,467,26
8792,U07,Puducherry,5,2014,1,Puducherry,GEN,PUVALA NAGESWARA RAO,M,GEN,60,IND,465,27
8793,U07,Puducherry,5,2014,1,Puducherry,GEN,G. PALANI,M,GEN,59,CPI(ML)(L),438,28
8794,U07,Puducherry,5,2014,1,Puducherry,GEN,MARIE UTHRIANATHAN,M,GEN,32,SAP,366,29
8795,U07,Puducherry,5,2014,1,Puducherry,GEN,S. CHITRAKALA,F,GEN,37,JD(U),309,30
8796,U07,Puducherry,5,2014,1,Puducherry,GEN,P. DHANARASU @ MATHIMAHARAJA,M,GEN,50,IND,198,31

In [13]:
ge14cw.drop(0, inplace = True)
ge14cw.drop(1, inplace = True)
ge14cw.drop(2, inplace = True)

In [14]:
ge14cw.reset_index(inplace=True)

In [15]:
del ge14cw['index']

In [16]:
ge14cw

2,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,GODAM NAGESH,M,ST,49,TRS,430847,1
1,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NARESH,M,ST,37,INC,259557,2
2,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RAMESH RATHOD,M,ST,48,TDP,184198,3
3,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RATHOD SADASHIV,M,ST,55,BSP,94420,4
4,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NETHAWATH RAMDAS,M,ST,44,IND,41032,5
5,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,None of the Above,NaN,NaN,NaN,NOTA,17084,6
6,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,MOSALI CHINNAIAH,M,ST,40,IND,8859,7
7,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,PAWAR KRISHNA,M,ST,33,IND,5055,8
8,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,BANKA SAHADEV,M,ST,53,IND,4787,9
9,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BALKA SUMAN,M,SC,31,TRS,565496,1
10,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,G. VIVEKANAND,M,SC,56,INC,274338,2
11,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,DR.JANAPATI SARAT BABU,M,SC,42,TDP,63334,3
12,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VELTHURU MALLAIAH,M,SC,57,RP(K),45977,4
13,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,TAGARAM SHANKAR LAL,M,SC,37,BSP,9449,5
14,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SHANKAR,M,SC,44,PPOI,9290,6
15,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,JINNA RAMADEVI,F,SC,37,IND,9199,7
16,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SANJEEV,M,SC,37,RPI,8609,8
17,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BUPELLI NARAYANA,M,SC,30,IND,7258,9
18,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,None of the Above,NaN,NaN,NaN,NOTA,5361,10
19,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VENKATA SWAMY INJAM,M,SC,42,MaSP,3866,11
20,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,THALLAPALLI SRINIVAS,M,SC,35,IND,3699,12
21,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GADDALA VINAY KUMAR,M,SC,65,IND,3266,13
22,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,J.V. RAJU,M,SC,50,NIP,3020,14
23,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KAMILLA JAYA RAO,M,SC,43,IND,2742,15
24,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,MOUTAM RAVINDER,M,SC,33,IND,2674,16
25,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GORRE RAMESH,M,SC,43,IND,2361,17
26,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BOTHA VENKATA MALLAIAH,M,SC,58,BCUF,2245,18
27,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,54,TRS,505358,1
28,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,47,INC,300706,2
29,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,CHENNAMANENI VIDYA SAGAR RAO,M,GEN,73,BJP,214828,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8764,U07,Puducherry,5,2014,1,Puducherry,GEN,V. NARAYANASAMY,M,GEN,66,INC,194972,2
8765,U07,Puducherry,5,2014,1,Puducherry,GEN,M.V. OMALINGAM,M,GEN,42,ADMK,132657,3
8766,U07,Puducherry,5,2014,1,Puducherry,GEN,A.M.H. NAZEEM,M,GEN,52,DMK,60580,4
8767,U07,Puducherry,5,2014,1,Puducherry,GEN,R.K.R. ANANTHARAMAN,M,GEN,41,PMK,22754,5
8768,U07,Puducherry,5,2014,1,Puducherry,GEN,None of the Above,NaN,NaN,NaN,NOTA,22268,6
8769,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VISWANATHAN,M,GEN,64,CPI,12709,7
8770,U07,Puducherry,5,2014,1,Puducherry,GEN,DR. V. RANGARAJAN,M,GEN,59,AAAP,8307,8
8771,U07,Puducherry,5,2014,1,Puducherry,GEN,SANJIVGANTHI .S,M,SC,30,IND,5896,9
8772,U07,Puducherry,5,2014,1,Puducherry,GEN,P. ASARAVEL,M,SC,41,IND,3472,10
8773,U07,Puducherry,5,2014,1,Puducherry,GEN,PROFESSOR M. RAMADASS,M,GEN,64,IND,2494,11
8774,U07,Puducherry,5,2014,1,Puducherry,GEN,S. KRISHNAMOORTHY,M,SC,48,BSP,2060,12
8775,U07,Puducherry,5,2014,1,Puducherry,GEN,S. EZHILARASAN,M,SC,41,IND,1777,13
8776,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SHANMUGAM,M,GEN,50,IND,1726,14
8777,U07,Puducherry,5,2014,1,Puducherry,GEN,RAMAMURTHI,M,GEN,53,IND,1442,15
8778,U07,Puducherry,5,2014,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,37,IND,1340,16
8779,U07,Puducherry,5,2014,1,Puducherry,GEN,S. SUDARSANAN,M,GEN,37,IND,1270,17
8780,U07,Puducherry,5,2014,1,Puducherry,GEN,K. RAMADASS,M,SC,49,IND,1236,18
8781,U07,Puducherry,5,2014,1,Puducherry,GEN,J. DHANDAPANI,M,GEN,61,IND,1144,19
8782,U07,Puducherry,5,2014,1,Puducherry,GEN,K. MANJINI,M,GEN,41,IND,767,20
8783,U07,Puducherry,5,2014,1,Puducherry,GEN,KALIAYAMURTHY,M,SC,44,IND,747,21
8784,U07,Puducherry,5,2014,1,Puducherry,GEN,V. VIJAYA,F,GEN,29,IND,746,22
8785,U07,Puducherry,5,2014,1,Puducherry,GEN,P. BAKKIARAJ,M,SC,31,IND,610,23
8786,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VALAVAN,M,GEN,40,IND,497,24
8787,U07,Puducherry,5,2014,1,Puducherry,GEN,I. SENTHIL KUMAR,M,GEN,31,IND,477,25
8788,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SUTHA,F,SC,30,IND,467,26
8789,U07,Puducherry,5,2014,1,Puducherry,GEN,PUVALA NAGESWARA RAO,M,GEN,60,IND,465,27
8790,U07,Puducherry,5,2014,1,Puducherry,GEN,G. PALANI,M,GEN,59,CPI(ML)(L),438,28
8791,U07,Puducherry,5,2014,1,Puducherry,GEN,MARIE UTHRIANATHAN,M,GEN,32,SAP,366,29
8792,U07,Puducherry,5,2014,1,Puducherry,GEN,S. CHITRAKALA,F,GEN,37,JD(U),309,30
8793,U07,Puducherry,5,2014,1,Puducherry,GEN,P. DHANARASU @ MATHIMAHARAJA,M,GEN,50,IND,198,31

In [17]:
ge14cw.to_csv('CW2014.csv',index=False)

In [18]:
cw=pd.read_csv('CW2014.csv')

In [19]:
cw

,ST_CODE,State name,Month,Year,PC Number,PC name,PC Type,Candidate Name,Candidate Sex,Candidate Category,Candidate Age,Party Abbreviation,Total Votes Polled,Position
0,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,GODAM NAGESH,M,ST,49.0,TRS,430847,1
1,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NARESH,M,ST,37.0,INC,259557,2
2,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RAMESH RATHOD,M,ST,48.0,TDP,184198,3
3,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,RATHOD SADASHIV,M,ST,55.0,BSP,94420,4
4,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,NETHAWATH RAMDAS,M,ST,44.0,IND,41032,5
5,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,None of the Above,NaN,NaN,NaN,NOTA,17084,6
6,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,MOSALI CHINNAIAH,M,ST,40.0,IND,8859,7
7,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,PAWAR KRISHNA,M,ST,33.0,IND,5055,8
8,S01,Andhra Pradesh,5,2014,1,Adilabad,ST,BANKA SAHADEV,M,ST,53.0,IND,4787,9
9,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BALKA SUMAN,M,SC,31.0,TRS,565496,1
10,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,G. VIVEKANAND,M,SC,56.0,INC,274338,2
11,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,DR.JANAPATI SARAT BABU,M,SC,42.0,TDP,63334,3
12,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VELTHURU MALLAIAH,M,SC,57.0,RP(K),45977,4
13,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,TAGARAM SHANKAR LAL,M,SC,37.0,BSP,9449,5
14,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SHANKAR,M,SC,44.0,PPOI,9290,6
15,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,JINNA RAMADEVI,F,SC,37.0,IND,9199,7
16,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KALVALA SANJEEV,M,SC,37.0,RPI,8609,8
17,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BUPELLI NARAYANA,M,SC,30.0,IND,7258,9
18,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,None of the Above,NaN,NaN,NaN,NOTA,5361,10
19,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,VENKATA SWAMY INJAM,M,SC,42.0,MaSP,3866,11
20,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,THALLAPALLI SRINIVAS,M,SC,35.0,IND,3699,12
21,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GADDALA VINAY KUMAR,M,SC,65.0,IND,3266,13
22,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,J.V. RAJU,M,SC,50.0,NIP,3020,14
23,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,KAMILLA JAYA RAO,M,SC,43.0,IND,2742,15
24,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,MOUTAM RAVINDER,M,SC,33.0,IND,2674,16
25,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,GORRE RAMESH,M,SC,43.0,IND,2361,17
26,S01,Andhra Pradesh,5,2014,2,Peddapalle,SC,BOTHA VENKATA MALLAIAH,M,SC,58.0,BCUF,2245,18
27,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,VINOD KUMAR BOINAPALLY,M,GEN,54.0,TRS,505358,1
28,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,PONNAM PRABHAKAR,M,GEN,47.0,INC,300706,2
29,S01,Andhra Pradesh,5,2014,3,Karimnagar,GEN,CHENNAMANENI VIDYA SAGAR RAO,M,GEN,73.0,BJP,214828,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8764,U07,Puducherry,5,2014,1,Puducherry,GEN,V. NARAYANASAMY,M,GEN,66.0,INC,194972,2
8765,U07,Puducherry,5,2014,1,Puducherry,GEN,M.V. OMALINGAM,M,GEN,42.0,ADMK,132657,3
8766,U07,Puducherry,5,2014,1,Puducherry,GEN,A.M.H. NAZEEM,M,GEN,52.0,DMK,60580,4
8767,U07,Puducherry,5,2014,1,Puducherry,GEN,R.K.R. ANANTHARAMAN,M,GEN,41.0,PMK,22754,5
8768,U07,Puducherry,5,2014,1,Puducherry,GEN,None of the Above,NaN,NaN,NaN,NOTA,22268,6
8769,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VISWANATHAN,M,GEN,64.0,CPI,12709,7
8770,U07,Puducherry,5,2014,1,Puducherry,GEN,DR. V. RANGARAJAN,M,GEN,59.0,AAAP,8307,8
8771,U07,Puducherry,5,2014,1,Puducherry,GEN,SANJIVGANTHI .S,M,SC,30.0,IND,5896,9
8772,U07,Puducherry,5,2014,1,Puducherry,GEN,P. ASARAVEL,M,SC,41.0,IND,3472,10
8773,U07,Puducherry,5,2014,1,Puducherry,GEN,PROFESSOR M. RAMADASS,M,GEN,64.0,IND,2494,11
8774,U07,Puducherry,5,2014,1,Puducherry,GEN,S. KRISHNAMOORTHY,M,SC,48.0,BSP,2060,12
8775,U07,Puducherry,5,2014,1,Puducherry,GEN,S. EZHILARASAN,M,SC,41.0,IND,1777,13
8776,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SHANMUGAM,M,GEN,50.0,IND,1726,14
8777,U07,Puducherry,5,2014,1,Puducherry,GEN,RAMAMURTHI,M,GEN,53.0,IND,1442,15
8778,U07,Puducherry,5,2014,1,Puducherry,GEN,M. CHITTIBABU,M,GEN,37.0,IND,1340,16
8779,U07,Puducherry,5,2014,1,Puducherry,GEN,S. SUDARSANAN,M,GEN,37.0,IND,1270,17
8780,U07,Puducherry,5,2014,1,Puducherry,GEN,K. RAMADASS,M,SC,49.0,IND,1236,18
8781,U07,Puducherry,5,2014,1,Puducherry,GEN,J. DHANDAPANI,M,GEN,61.0,IND,1144,19
8782,U07,Puducherry,5,2014,1,Puducherry,GEN,K. MANJINI,M,GEN,41.0,IND,767,20
8783,U07,Puducherry,5,2014,1,Puducherry,GEN,KALIAYAMURTHY,M,SC,44.0,IND,747,21
8784,U07,Puducherry,5,2014,1,Puducherry,GEN,V. VIJAYA,F,GEN,29.0,IND,746,22
8785,U07,Puducherry,5,2014,1,Puducherry,GEN,P. BAKKIARAJ,M,SC,31.0,IND,610,23
8786,U07,Puducherry,5,2014,1,Puducherry,GEN,R. VALAVAN,M,GEN,40.0,IND,497,24
8787,U07,Puducherry,5,2014,1,Puducherry,GEN,I. SENTHIL KUMAR,M,GEN,31.0,IND,477,25
8788,U07,Puducherry,5,2014,1,Puducherry,GEN,G. SUTHA,F,SC,30.0,IND,467,26
8789,U07,Puducherry,5,2014,1,Puducherry,GEN,PUVALA NAGESWARA RAO,M,GEN,60.0,IND,465,27
8790,U07,Puducherry,5,2014,1,Puducherry,GEN,G. PALANI,M,GEN,59.0,CPI(ML)(L),438,28
8791,U07,Puducherry,5,2014,1,Puducherry,GEN,MARIE UTHRIANATHAN,M,GEN,32.0,SAP,366,29
8792,U07,Puducherry,5,2014,1,Puducherry,GEN,S. CHITRAKALA,F,GEN,37.0,JD(U),309,30
8793,U07,Puducherry,5,2014,1,Puducherry,GEN,P. DHANARASU @ MATHIMAHARAJA,M,GEN,50.0,IND,198,31

In [20]:
age = cw.pivot_table(values=['Candidate Age'],index=['State name'],columns=['Candidate Sex'], aggfunc=len)

In [21]:
age

                          Candidate Age
Candidate Sex                         F       M    O
State name
Andaman & Nicobar Islands           2.0    13.0  NaN
Andhra Pradesh                     43.0   555.0  NaN
Arunachal Pradesh                   NaN    11.0  NaN
Assam                              16.0   146.0  NaN
Bihar                              47.0   560.0  NaN
Chandigarh                          5.0    12.0  NaN
Chattisgarh                        21.0   190.0  NaN
Dadra & Nagar Haveli                1.0    10.0  NaN
Daman & Diu                         NaN     4.0  NaN
Goa                                 2.0    17.0  NaN
Gujarat                            16.0   318.0  NaN
Haryana                            11.0   219.0  NaN
Himachal Pradesh                    5.0    33.0  NaN
Jammu & Kashmir                     3.0    74.0  NaN
Jharkhand                          18.0   222.0  NaN
Karnataka                          20.0   413.0  1.0
Kerala                             27.0   242.0  NaN
Lakshadweep                         NaN     6.0  NaN
Madhya Pradesh                     37.0   341.0  NaN
Maharashtra                        69.0   827.0  1.0
Manipur                             2.0    16.0  NaN
Meghalaya                           1.0     9.0  NaN
Mizoram                             NaN     3.0  NaN
NCT OF Delhi                       13.0   137.0  NaN
Nagaland                            NaN     3.0  NaN
Odisha                             17.0   179.0  NaN
Puducherry                          3.0    27.0  NaN
Punjab                             20.0   233.0  NaN
Rajasthan                          27.0   293.0  NaN
Sikkim                              NaN     6.0  NaN
Tamil Nadu                         55.0   790.0  1.0
Tripura                             3.0    22.0  NaN
Uttar Pradesh                     126.0  1159.0  3.0
Uttarakhand                         7.0    67.0  NaN
West Bengal                        51.0   421.0  NaN

In [22]:
a=age['Candidate Age','F']
b=age['Candidate Age','M']

In [23]:
def gcd(a,b):
    if b>a:
        while b > 0:
            a, b = b, a % b
        return a
    elif a>b:
        while a > 0:
            b, a = a, b % a
        return b
    else:
        return 1

In [24]:
age.reset_index(inplace=True)

In [25]:
age.fillna(value=0)

                              State name Candidate Age
Candidate Sex                                        F       M    O
0              Andaman & Nicobar Islands           2.0    13.0  0.0
1                         Andhra Pradesh          43.0   555.0  0.0
2                      Arunachal Pradesh           0.0    11.0  0.0
3                                  Assam          16.0   146.0  0.0
4                                  Bihar          47.0   560.0  0.0
5                             Chandigarh           5.0    12.0  0.0
6                            Chattisgarh          21.0   190.0  0.0
7                   Dadra & Nagar Haveli           1.0    10.0  0.0
8                            Daman & Diu           0.0     4.0  0.0
9                                    Goa           2.0    17.0  0.0
10                               Gujarat          16.0   318.0  0.0
11                               Haryana          11.0   219.0  0.0
12                      Himachal Pradesh           5.0    33.0  0.0
13                       Jammu & Kashmir           3.0    74.0  0.0
14                             Jharkhand          18.0   222.0  0.0
15                             Karnataka          20.0   413.0  1.0
16                                Kerala          27.0   242.0  0.0
17                           Lakshadweep           0.0     6.0  0.0
18                        Madhya Pradesh          37.0   341.0  0.0
19                           Maharashtra          69.0   827.0  1.0
20                               Manipur           2.0    16.0  0.0
21                             Meghalaya           1.0     9.0  0.0
22                               Mizoram           0.0     3.0  0.0
23                          NCT OF Delhi          13.0   137.0  0.0
24                              Nagaland           0.0     3.0  0.0
25                                Odisha          17.0   179.0  0.0
26                            Puducherry           3.0    27.0  0.0
27                                Punjab          20.0   233.0  0.0
28                             Rajasthan          27.0   293.0  0.0
29                                Sikkim           0.0     6.0  0.0
30                            Tamil Nadu          55.0   790.0  1.0
31                               Tripura           3.0    22.0  0.0
32                         Uttar Pradesh         126.0  1159.0  3.0
33                           Uttarakhand           7.0    67.0  0.0
34                           West Bengal          51.0   421.0  0.0

In [26]:
age.columns = age.columns.get_level_values(1)

In [27]:
ca = list(age.columns)

In [28]:
ca[0]='STATE'

In [29]:
age.columns = ca

In [30]:
age

                        STATE      F       M    O
0   Andaman & Nicobar Islands    2.0    13.0  NaN
1              Andhra Pradesh   43.0   555.0  NaN
2           Arunachal Pradesh    NaN    11.0  NaN
3                       Assam   16.0   146.0  NaN
4                       Bihar   47.0   560.0  NaN
5                  Chandigarh    5.0    12.0  NaN
6                 Chattisgarh   21.0   190.0  NaN
7        Dadra & Nagar Haveli    1.0    10.0  NaN
8                 Daman & Diu    NaN     4.0  NaN
9                         Goa    2.0    17.0  NaN
10                    Gujarat   16.0   318.0  NaN
11                    Haryana   11.0   219.0  NaN
12           Himachal Pradesh    5.0    33.0  NaN
13            Jammu & Kashmir    3.0    74.0  NaN
14                  Jharkhand   18.0   222.0  NaN
15                  Karnataka   20.0   413.0  1.0
16                     Kerala   27.0   242.0  NaN
17                Lakshadweep    NaN     6.0  NaN
18             Madhya Pradesh   37.0   341.0  NaN
19                Maharashtra   69.0   827.0  1.0
20                    Manipur    2.0    16.0  NaN
21                  Meghalaya    1.0     9.0  NaN
22                    Mizoram    NaN     3.0  NaN
23               NCT OF Delhi   13.0   137.0  NaN
24                   Nagaland    NaN     3.0  NaN
25                     Odisha   17.0   179.0  NaN
26                 Puducherry    3.0    27.0  NaN
27                     Punjab   20.0   233.0  NaN
28                  Rajasthan   27.0   293.0  NaN
29                     Sikkim    NaN     6.0  NaN
30                 Tamil Nadu   55.0   790.0  1.0
31                    Tripura    3.0    22.0  NaN
32              Uttar Pradesh  126.0  1159.0  3.0
33                Uttarakhand    7.0    67.0  NaN
34                West Bengal   51.0   421.0  NaN

In [31]:
x = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in age.index:
    x[i] = gcd(a[i],b[i])

In [32]:
f=a/x.copy()
m=b/x.copy()

In [33]:
f=pd.Series.to_frame(f)
f.reset_index(inplace=True)

In [34]:
m=pd.Series.to_frame(m)
m.reset_index(inplace=True)

In [35]:
m.columns = m.columns.get_level_values(1)

In [36]:
ck = list(m.columns)

In [37]:
ck[0]='STATE'
ck[1]='Male_Candidates'

In [38]:
m.columns= ck

In [39]:
m

                        STATE  Male_Candidates
0   Andaman & Nicobar Islands             13.0
1              Andhra Pradesh            555.0
2           Arunachal Pradesh             11.0
3                       Assam             73.0
4                       Bihar            560.0
5                  Chandigarh             12.0
6                 Chattisgarh            190.0
7        Dadra & Nagar Haveli             10.0
8                 Daman & Diu              4.0
9                         Goa             17.0
10                    Gujarat            159.0
11                    Haryana            219.0
12           Himachal Pradesh             33.0
13            Jammu & Kashmir             74.0
14                  Jharkhand             37.0
15                  Karnataka            413.0
16                     Kerala            242.0
17                Lakshadweep              6.0
18             Madhya Pradesh            341.0
19                Maharashtra            827.0
20                    Manipur              8.0
21                  Meghalaya              9.0
22                    Mizoram              3.0
23               NCT OF Delhi            137.0
24                   Nagaland              3.0
25                     Odisha            179.0
26                 Puducherry              9.0
27                     Punjab            233.0
28                  Rajasthan            293.0
29                     Sikkim              6.0
30                 Tamil Nadu            158.0
31                    Tripura             22.0
32              Uttar Pradesh           1159.0
33                Uttarakhand             67.0
34                West Bengal            421.0

In [40]:
f.columns = f.columns.get_level_values(1)

In [41]:
cl = list(f.columns)

In [42]:
cl[0]='STATE'
cl[1]='Female_Candidates'

In [43]:
f.columns= cl

In [44]:
o=pd.merge(age,f,on='STATE')

In [45]:
oge=pd.merge(o,m,on='STATE')

In [46]:
oge.fillna(value=0,inplace=True)

In [47]:
oge

,STATE,F,M,O,Female_Candidates,Male_Candidates
0,Andaman & Nicobar Islands,2.0,13.0,0.0,2.0,13.0
1,Andhra Pradesh,43.0,555.0,0.0,43.0,555.0
2,Arunachal Pradesh,0.0,11.0,0.0,0.0,11.0
3,Assam,16.0,146.0,0.0,8.0,73.0
4,Bihar,47.0,560.0,0.0,47.0,560.0
5,Chandigarh,5.0,12.0,0.0,5.0,12.0
6,Chattisgarh,21.0,190.0,0.0,21.0,190.0
7,Dadra & Nagar Haveli,1.0,10.0,0.0,1.0,10.0
8,Daman & Diu,0.0,4.0,0.0,0.0,4.0
9,Goa,2.0,17.0,0.0,2.0,17.0
10,Gujarat,16.0,318.0,0.0,8.0,159.0
11,Haryana,11.0,219.0,0.0,11.0,219.0
12,Himachal Pradesh,5.0,33.0,0.0,5.0,33.0
13,Jammu & Kashmir,3.0,74.0,0.0,3.0,74.0
14,Jharkhand,18.0,222.0,0.0,3.0,37.0
15,Karnataka,20.0,413.0,1.0,20.0,413.0
16,Kerala,27.0,242.0,0.0,27.0,242.0
17,Lakshadweep,0.0,6.0,0.0,0.0,6.0
18,Madhya Pradesh,37.0,341.0,0.0,37.0,341.0
19,Maharashtra,69.0,827.0,1.0,69.0,827.0
20,Manipur,2.0,16.0,0.0,1.0,8.0
21,Meghalaya,1.0,9.0,0.0,1.0,9.0
22,Mizoram,0.0,3.0,0.0,0.0,3.0
23,NCT OF Delhi,13.0,137.0,0.0,13.0,137.0
24,Nagaland,0.0,3.0,0.0,0.0,3.0
25,Odisha,17.0,179.0,0.0,17.0,179.0
26,Puducherry,3.0,27.0,0.0,1.0,9.0
27,Punjab,20.0,233.0,0.0,20.0,233.0
28,Rajasthan,27.0,293.0,0.0,27.0,293.0
29,Sikkim,0.0,6.0,0.0,0.0,6.0
30,Tamil Nadu,55.0,790.0,1.0,11.0,158.0
31,Tripura,3.0,22.0,0.0,3.0,22.0
32,Uttar Pradesh,126.0,1159.0,3.0,126.0,1159.0
33,Uttarakhand,7.0,67.0,0.0,7.0,67.0
34,West Bengal,51.0,421.0,0.0,51.0,421.0

In [48]:
oge['FtoM_ratio'] = oge['Female_Candidates'].astype(str).str.cat(oge['Male_Candidates'].astype(str), sep=' : ')

In [49]:
oge

,STATE,F,M,O,Female_Candidates,Male_Candidates,FtoM_ratio
0,Andaman & Nicobar Islands,2.0,13.0,0.0,2.0,13.0,2.0 : 13.0
1,Andhra Pradesh,43.0,555.0,0.0,43.0,555.0,43.0 : 555.0
2,Arunachal Pradesh,0.0,11.0,0.0,0.0,11.0,0.0 : 11.0
3,Assam,16.0,146.0,0.0,8.0,73.0,8.0 : 73.0
4,Bihar,47.0,560.0,0.0,47.0,560.0,47.0 : 560.0
5,Chandigarh,5.0,12.0,0.0,5.0,12.0,5.0 : 12.0
6,Chattisgarh,21.0,190.0,0.0,21.0,190.0,21.0 : 190.0
7,Dadra & Nagar Haveli,1.0,10.0,0.0,1.0,10.0,1.0 : 10.0
8,Daman & Diu,0.0,4.0,0.0,0.0,4.0,0.0 : 4.0
9,Goa,2.0,17.0,0.0,2.0,17.0,2.0 : 17.0
10,Gujarat,16.0,318.0,0.0,8.0,159.0,8.0 : 159.0
11,Haryana,11.0,219.0,0.0,11.0,219.0,11.0 : 219.0
12,Himachal Pradesh,5.0,33.0,0.0,5.0,33.0,5.0 : 33.0
13,Jammu & Kashmir,3.0,74.0,0.0,3.0,74.0,3.0 : 74.0
14,Jharkhand,18.0,222.0,0.0,3.0,37.0,3.0 : 37.0
15,Karnataka,20.0,413.0,1.0,20.0,413.0,20.0 : 413.0
16,Kerala,27.0,242.0,0.0,27.0,242.0,27.0 : 242.0
17,Lakshadweep,0.0,6.0,0.0,0.0,6.0,0.0 : 6.0
18,Madhya Pradesh,37.0,341.0,0.0,37.0,341.0,37.0 : 341.0
19,Maharashtra,69.0,827.0,1.0,69.0,827.0,69.0 : 827.0
20,Manipur,2.0,16.0,0.0,1.0,8.0,1.0 : 8.0
21,Meghalaya,1.0,9.0,0.0,1.0,9.0,1.0 : 9.0
22,Mizoram,0.0,3.0,0.0,0.0,3.0,0.0 : 3.0
23,NCT OF Delhi,13.0,137.0,0.0,13.0,137.0,13.0 : 137.0
24,Nagaland,0.0,3.0,0.0,0.0,3.0,0.0 : 3.0
25,Odisha,17.0,179.0,0.0,17.0,179.0,17.0 : 179.0
26,Puducherry,3.0,27.0,0.0,1.0,9.0,1.0 : 9.0
27,Punjab,20.0,233.0,0.0,20.0,233.0,20.0 : 233.0
28,Rajasthan,27.0,293.0,0.0,27.0,293.0,27.0 : 293.0
29,Sikkim,0.0,6.0,0.0,0.0,6.0,0.0 : 6.0
30,Tamil Nadu,55.0,790.0,1.0,11.0,158.0,11.0 : 158.0
31,Tripura,3.0,22.0,0.0,3.0,22.0,3.0 : 22.0
32,Uttar Pradesh,126.0,1159.0,3.0,126.0,1159.0,126.0 : 1159.0
33,Uttarakhand,7.0,67.0,0.0,7.0,67.0,7.0 : 67.0
34,West Bengal,51.0,421.0,0.0,51.0,421.0,51.0 : 421.0

In [50]:
del oge['Male_Candidates']

In [51]:
del oge['Female_Candidates']

In [52]:
oge

                        STATE      F       M    O      FtoM_ratio
0   Andaman & Nicobar Islands    2.0    13.0  0.0      2.0 : 13.0
1              Andhra Pradesh   43.0   555.0  0.0    43.0 : 555.0
2           Arunachal Pradesh    0.0    11.0  0.0      0.0 : 11.0
3                       Assam   16.0   146.0  0.0      8.0 : 73.0
4                       Bihar   47.0   560.0  0.0    47.0 : 560.0
5                  Chandigarh    5.0    12.0  0.0      5.0 : 12.0
6                 Chattisgarh   21.0   190.0  0.0    21.0 : 190.0
7        Dadra & Nagar Haveli    1.0    10.0  0.0      1.0 : 10.0
8                 Daman & Diu    0.0     4.0  0.0       0.0 : 4.0
9                         Goa    2.0    17.0  0.0      2.0 : 17.0
10                    Gujarat   16.0   318.0  0.0     8.0 : 159.0
11                    Haryana   11.0   219.0  0.0    11.0 : 219.0
12           Himachal Pradesh    5.0    33.0  0.0      5.0 : 33.0
13            Jammu & Kashmir    3.0    74.0  0.0      3.0 : 74.0
14                  Jharkhand   18.0   222.0  0.0      3.0 : 37.0
15                  Karnataka   20.0   413.0  1.0    20.0 : 413.0
16                     Kerala   27.0   242.0  0.0    27.0 : 242.0
17                Lakshadweep    0.0     6.0  0.0       0.0 : 6.0
18             Madhya Pradesh   37.0   341.0  0.0    37.0 : 341.0
19                Maharashtra   69.0   827.0  1.0    69.0 : 827.0
20                    Manipur    2.0    16.0  0.0       1.0 : 8.0
21                  Meghalaya    1.0     9.0  0.0       1.0 : 9.0
22                    Mizoram    0.0     3.0  0.0       0.0 : 3.0
23               NCT OF Delhi   13.0   137.0  0.0    13.0 : 137.0
24                   Nagaland    0.0     3.0  0.0       0.0 : 3.0
25                     Odisha   17.0   179.0  0.0    17.0 : 179.0
26                 Puducherry    3.0    27.0  0.0       1.0 : 9.0
27                     Punjab   20.0   233.0  0.0    20.0 : 233.0
28                  Rajasthan   27.0   293.0  0.0    27.0 : 293.0
29                     Sikkim    0.0     6.0  0.0       0.0 : 6.0
30                 Tamil Nadu   55.0   790.0  1.0    11.0 : 158.0
31                    Tripura    3.0    22.0  0.0      3.0 : 22.0
32              Uttar Pradesh  126.0  1159.0  3.0  126.0 : 1159.0
33                Uttarakhand    7.0    67.0  0.0      7.0 : 67.0
34                West Bengal   51.0   421.0  0.0    51.0 : 421.0

In [53]:
s2014.reset_index(inplace=True)

In [64]:
s2014['STATE'][6]='Chattisgarh'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [65]:
s2014.to_csv('s2014.csv',index=False)

In [66]:
s2014=pd.read_csv('s2014.csv')

In [67]:
s2014

                        STATE  Total voters  Total_Electors  POLL_PERC in %
0   Andaman & Nicobar Islands        190346          269360       70.666023
1              Andhra Pradesh      48467721        64934138       74.641356
2           Arunachal Pradesh        600828          759344       79.124613
3                       Assam      15092387        18837713       80.117937
4                       Bihar      35892459        63800160       56.257632
5                  Chandigarh        453462          615214       73.708011
6                 Chattisgarh      12256962        17664520       69.387461
7        Dadra & Nagar Haveli        165324          196597       84.092840
8                 Daman & Diu         87233          111827       78.007100
9                         Goa        817440         1060777       77.060494
10                    Gujarat      25849655        40603104       63.664234
11                    Haryana      11501251        16097233       71.448621
12           Himachal Pradesh       3100199         4810071       64.452250
13            Jammu & Kashmir       3571537         7183129       49.721187
14                  Jharkhand      12986625        20349796       63.816979
15                  Karnataka      31053583        46209813       67.201274
16                     Kerala      17987124        24326650       73.939996
17                Lakshadweep         43242           49922       86.619126
18             Madhya Pradesh      29648105        48121301       61.611188
19                Maharashtra      48740403        80798823       60.323160
20                    Manipur       1415131         1774369       79.754042
21                  Meghalaya       1078295         1567241       68.802118
22                    Mizoram        434962          702170       61.945398
23               NCT OF Delhi       8275146        12711164       65.101402
24                   Nagaland       1039962         1182972       87.910956
25                     Odisha      21542724        29196045       73.786446
26                 Puducherry        740053          901357       82.104316
27                     Punjab      13849496        19608161       70.631285
28                  Rajasthan      27133776        42994657       63.109646
29                     Sikkim        310095          370770       83.635407
30                 Tamil Nadu      40644282        55114867       73.744679
31                    Tripura       2028707         2388822       84.924997
32              Uttar Pradesh      81118615       138810557       58.438361
33                Uttarakhand       4395561         7127057       61.674279
34                West Bengal      51662564        62833113       82.221876

In [68]:
output = pd.merge(oge,s2014,on='STATE')

In [69]:
output

,STATE,F,M,O,FtoM_ratio,Total voters,Total_Electors,POLL_PERC in %
0,Andaman & Nicobar Islands,2.0,13.0,0.0,2.0 : 13.0,190346,269360,70.666023
1,Andhra Pradesh,43.0,555.0,0.0,43.0 : 555.0,48467721,64934138,74.641356
2,Arunachal Pradesh,0.0,11.0,0.0,0.0 : 11.0,600828,759344,79.124613
3,Assam,16.0,146.0,0.0,8.0 : 73.0,15092387,18837713,80.117937
4,Bihar,47.0,560.0,0.0,47.0 : 560.0,35892459,63800160,56.257632
5,Chandigarh,5.0,12.0,0.0,5.0 : 12.0,453462,615214,73.708011
6,Chattisgarh,21.0,190.0,0.0,21.0 : 190.0,12256962,17664520,69.387461
7,Dadra & Nagar Haveli,1.0,10.0,0.0,1.0 : 10.0,165324,196597,84.092840
8,Daman & Diu,0.0,4.0,0.0,0.0 : 4.0,87233,111827,78.007100
9,Goa,2.0,17.0,0.0,2.0 : 17.0,817440,1060777,77.060494
10,Gujarat,16.0,318.0,0.0,8.0 : 159.0,25849655,40603104,63.664234
11,Haryana,11.0,219.0,0.0,11.0 : 219.0,11501251,16097233,71.448621
12,Himachal Pradesh,5.0,33.0,0.0,5.0 : 33.0,3100199,4810071,64.452250
13,Jammu & Kashmir,3.0,74.0,0.0,3.0 : 74.0,3571537,7183129,49.721187
14,Jharkhand,18.0,222.0,0.0,3.0 : 37.0,12986625,20349796,63.816979
15,Karnataka,20.0,413.0,1.0,20.0 : 413.0,31053583,46209813,67.201274
16,Kerala,27.0,242.0,0.0,27.0 : 242.0,17987124,24326650,73.939996
17,Lakshadweep,0.0,6.0,0.0,0.0 : 6.0,43242,49922,86.619126
18,Madhya Pradesh,37.0,341.0,0.0,37.0 : 341.0,29648105,48121301,61.611188
19,Maharashtra,69.0,827.0,1.0,69.0 : 827.0,48740403,80798823,60.323160
20,Manipur,2.0,16.0,0.0,1.0 : 8.0,1415131,1774369,79.754042
21,Meghalaya,1.0,9.0,0.0,1.0 : 9.0,1078295,1567241,68.802118
22,Mizoram,0.0,3.0,0.0,0.0 : 3.0,434962,702170,61.945398
23,NCT OF Delhi,13.0,137.0,0.0,13.0 : 137.0,8275146,12711164,65.101402
24,Nagaland,0.0,3.0,0.0,0.0 : 3.0,1039962,1182972,87.910956
25,Odisha,17.0,179.0,0.0,17.0 : 179.0,21542724,29196045,73.786446
26,Puducherry,3.0,27.0,0.0,1.0 : 9.0,740053,901357,82.104316
27,Punjab,20.0,233.0,0.0,20.0 : 233.0,13849496,19608161,70.631285
28,Rajasthan,27.0,293.0,0.0,27.0 : 293.0,27133776,42994657,63.109646
29,Sikkim,0.0,6.0,0.0,0.0 : 6.0,310095,370770,83.635407
30,Tamil Nadu,55.0,790.0,1.0,11.0 : 158.0,40644282,55114867,73.744679
31,Tripura,3.0,22.0,0.0,3.0 : 22.0,2028707,2388822,84.924997
32,Uttar Pradesh,126.0,1159.0,3.0,126.0 : 1159.0,81118615,138810557,58.438361
33,Uttarakhand,7.0,67.0,0.0,7.0 : 67.0,4395561,7127057,61.674279
34,West Bengal,51.0,421.0,0.0,51.0 : 421.0,51662564,62833113,82.221876

In [70]:
output.to_csv('GE2014_detail.csv',index=False)

In [72]:
g=cw[cw['Position']==1].copy()

In [73]:
pp=g.pivot_table(index=['State name','Party Abbreviation'],values='Total Votes Polled', aggfunc=len).copy()

In [75]:
g['Candidate Sex'].value_counts()

M    481
F     62
Name: Candidate Sex, dtype: int64

In [84]:
qw = pd.DataFrame(g['Candidate Sex'].value_counts())

In [85]:
qw.reset_index(inplace=True)

In [86]:
qw.rename(columns={'index':'Indicators','Candidate Sex':'Election 2014'},inplace=True)

In [87]:
qw['Indicators'][0]= 'Male in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [88]:
qw['Indicators'][1]= 'Female in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [89]:
qw

             Indicators  Election 2014
0    Male in LowerHouse            481
1  Female in LowerHouse             62

In [90]:
ind = pd.DataFrame(g['Party Abbreviation'].describe())

In [91]:
ind.reset_index(inplace=True)

In [92]:
ind.rename(columns={'index':'Indicators','Party Abbreviation':'Election 2014'},inplace=True)

In [93]:
ind['Indicators'][0]= 'Total seats contested for'
ind['Indicators'][1]= 'Number of Parties'
ind['Indicators'][2]= 'Party with majority'
ind['Indicators'][3]= 'Majority party eats won'

In [94]:
ind

                  Indicators Election 2014
0  Total seats contested for           543
1          Number of Parties            36
2        Party with majority           BJP
3    Majority party eats won           282