In [1]:
import pandas as pd
import numpy as np
import plotly as py
import seaborn as sb
%matplotlib inline
import xlrd

In [3]:
ge1999 = pd.ExcelFile('GE_1999.xls')

In [4]:
ge99el = ge1999.parse('electors')

In [7]:
ge99el

,ST_CODE,ST_NAME,PC_NO,PC_NAME,PC_TYPE,MONTH,YEAR,TOT_ELECTORS,TOT_VOTERS,TOT_CONTESTANT,POLL_PERCENT
0,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,985232,676413,3,68.66
1,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,911609,637051,4,69.88
2,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,949773,716703,4,75.46
3,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,1420606,914936,6,64.40
4,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,1085536,759883,6,70.00
5,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,1035708,764079,4,73.77
6,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,1171987,836085,7,71.34
7,S01,ANDHRA PRADESH,8,Rajahmundry,GEN,7,1999,1137225,823798,7,72.44
8,S01,ANDHRA PRADESH,9,Amalapuram,SC,7,1999,908257,685230,5,75.44
9,S01,ANDHRA PRADESH,10,Narasapur,GEN,7,1999,1020409,733626,3,71.90
10,S01,ANDHRA PRADESH,11,Eluru,GEN,7,1999,1147205,852429,8,74.30
11,S01,ANDHRA PRADESH,12,Machilipatnam,GEN,7,1999,1006429,730278,4,72.56
12,S01,ANDHRA PRADESH,13,Vijayawada,GEN,7,1999,1384393,947325,12,68.43
13,S01,ANDHRA PRADESH,14,Tenali,GEN,7,1999,960447,659306,5,68.65
14,S01,ANDHRA PRADESH,15,Guntur,GEN,7,1999,1239626,794709,10,64.11
15,S01,ANDHRA PRADESH,16,Bapatla,GEN,7,1999,1077815,727105,7,67.46
16,S01,ANDHRA PRADESH,17,Narasaraopet,GEN,7,1999,1262560,878186,6,69.56
17,S01,ANDHRA PRADESH,18,Ongole,GEN,7,1999,1190279,792803,8,66.61
18,S01,ANDHRA PRADESH,19,Nellore,SC,7,1999,1165144,786565,6,67.51
19,S01,ANDHRA PRADESH,20,Tirupathi,SC,7,1999,1199710,824694,6,68.74
20,S01,ANDHRA PRADESH,21,Chittoor,GEN,7,1999,1140219,853778,5,74.88
21,S01,ANDHRA PRADESH,22,Rajampet,GEN,7,1999,946311,678817,10,71.73
22,S01,ANDHRA PRADESH,23,Cuddapah,GEN,7,1999,1090670,739109,11,67.77
23,S01,ANDHRA PRADESH,24,Hindupur,GEN,7,1999,1151606,792868,6,68.85
24,S01,ANDHRA PRADESH,25,Anantapur,GEN,7,1999,1226314,772471,5,62.99
25,S01,ANDHRA PRADESH,26,Kurnool,GEN,7,1999,1163375,773629,5,66.50
26,S01,ANDHRA PRADESH,27,Nandyal,GEN,7,1999,1116553,749179,8,67.10
27,S01,ANDHRA PRADESH,28,Nagarkurnool,SC,7,1999,1212569,843025,5,69.52
28,S01,ANDHRA PRADESH,29,Mahabubnagar,GEN,7,1999,1249455,830725,8,66.49
29,S01,ANDHRA PRADESH,30,Hyderabad,GEN,7,1999,1567225,1083678,7,69.15
...,...,...,...,...,...,...,...,...,...,...,...
513,S25,WEST BENGAL,26,Serampore,GEN,7,1999,1325375,925995,5,69.87
514,S25,WEST BENGAL,27,Hooghly,GEN,7,1999,1160870,930831,5,80.18
515,S25,WEST BENGAL,28,Arambagh,GEN,7,1999,1143407,944408,4,82.60
516,S25,WEST BENGAL,29,Panskura,GEN,7,1999,986955,824564,4,83.55
517,S25,WEST BENGAL,30,Tamluk,GEN,7,1999,1098196,919886,6,83.76
518,S25,WEST BENGAL,31,Contai,GEN,7,1999,990917,823941,7,83.15
519,S25,WEST BENGAL,32,Midnapore,GEN,7,1999,1099512,862567,5,78.45
520,S25,WEST BENGAL,33,Jhargram,ST,7,1999,991504,803200,5,81.01
521,S25,WEST BENGAL,34,Purulia,GEN,7,1999,1008066,692271,9,68.67
522,S25,WEST BENGAL,35,Bankura,GEN,7,1999,1041325,741303,8,71.19
523,S25,WEST BENGAL,36,Vishnupur,SC,7,1999,1071817,846339,5,78.96
524,S25,WEST BENGAL,37,Durgapur,SC,7,1999,1212641,885335,5,73.01
525,S25,WEST BENGAL,38,Asansol,GEN,7,1999,1265480,829147,7,65.52
526,S25,WEST BENGAL,39,Burdwan,GEN,7,1999,1216764,984678,5,80.93
527,S25,WEST BENGAL,40,Katwa,GEN,7,1999,1183616,933089,6,78.83
528,S25,WEST BENGAL,41,Bolpur,GEN,7,1999,1037427,792871,4,76.43
529,S25,WEST BENGAL,42,Birbhum,SC,7,1999,1043876,734173,5,70.33
530,U01,ANDAMAN & NICOBAR ISLANDS,1,Andaman & Nicobar Islands,GEN,7,1999,247384,147102,5,59.46
531,U02,CHANDIGARH,1,Chandigarh,GEN,7,1999,585006,282879,16,48.35
532,U03,DADRA & NAGAR HAVELI,1,Dadra & Nagar Haveli,ST,7,1999,98376,73507,5,74.72
533,U04,DAMAN & DIU,1,Daman And Diu,GEN,7,1999,72216,51811,4,71.74
534,U05,NATIONAL CAPITAL TERRITORY OF DELHI,1,New Delhi,GEN,7,1999,543037,226866,12,41.78
535,U05,NATIONAL CAPITAL TERRITORY OF DELHI,2,South Delhi,GEN,7,1999,1194198,499990,12,41.87
536,U05,NATIONAL CAPITAL TERRITORY OF DELHI,3,Outer Delhi,GEN,7,1999,3103525,1287504,13,41.49
537,U05,NATIONAL CAPITAL TERRITORY OF DELHI,4,East Delhi,GEN,7,1999,2393813,1038278,20,43.37
538,U05,NATIONAL CAPITAL TERRITORY OF DELHI,5,Chandni Chowk,GEN,7,1999,376654,204453,15,54.28
539,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,529646,278297,13,52.54
540,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,571657,258309,12,45.19
541,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,37619,30174,4,80.21
542,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,701990,444174,9,63.27

In [8]:
ge99el.columns

Index(['ST_CODE', 'ST_NAME', 'PC_NO', 'PC_NAME', 'PC_TYPE', 'MONTH', 'YEAR',
       'TOT_ELECTORS', 'TOT_VOTERS', 'TOT_CONTESTANT', 'POLL_PERCENT'],
      dtype='object')

In [75]:
s1999 = pd.pivot_table(ge99el,index='ST_NAME',values=['TOT_VOTERS', 'TOT_ELECTORS', 'TOT_CONTESTANT'],aggfunc=sum)

In [76]:
s1999['POLL_PERC in %']=(s1999['TOT_VOTERS']/s1999['TOT_ELECTORS']*100)

In [77]:
s1999

,TOT_CONTESTANT,TOT_ELECTORS,TOT_VOTERS,POLL_PERC in %
ST_NAME,,,,
ANDAMAN & NICOBAR ISLANDS,5,247384,147102,59.463021
ANDHRA PRADESH,285,49654389,34332073,69.142071
ARUNACHAL PRADESH,6,611572,441231,72.147024
ASSAM,115,14290673,10182919,71.255699
BIHAR,497,58788098,36143272,61.480594
CHANDIGARH,16,585006,282879,48.354889
DADRA & NAGAR HAVELI,5,98376,73507,74.720460
DAMAN & DIU,4,72216,51811,71.744489
GOA,16,908849,409944,45.105843
GUJARAT,159,29512402,13878611,47.026369
HARYANA,114,11038955,7029964,63.683238
HIMACHAL PRADESH,22,3786479,2149816,56.776124
JAMMU & KASHMIR,83,5030094,1626945,32.344227
KARNATAKA,130,34284098,23168337,67.577502
KERALA,142,22058901,15482676,70.187885
LAKSHADWEEP,4,37619,30174,80.209469
MADHYA PRADESH,344,46915473,25746824,54.879174
MAHARASHTRA,261,56853196,34660007,60.964043
MANIPUR,18,1372339,901242,65.671966
MEGHALAYA,14,1178250,661657,56.155909
MIZORAM,7,449406,293513,65.311322
NAGALAND,5,955914,728843,76.245666
NATIONAL CAPITAL TERRITORY OF DELHI,97,8712530,3793697,43.543001
ORISSA,105,24187490,13456534,55.634272
PONDICHERRY,9,701990,444174,63.273551
PUNJAB,120,15717304,8819200,56.111404
RAJASTHAN,165,31106488,16754016,53.860198
SIKKIM,4,255377,208670,81.710569
TAMIL NADU,362,47733664,27676543,57.981183
TRIPURA,17,1796055,1223784,68.137334
UTTAR PRADESH,1208,102946404,55107957,53.530726
WEST BENGAL,309,47649856,35761182,75.049927

In [78]:
ge99cw = ge1999.parse('cand_wise')

In [79]:
ge99cw.columns = ge99cw.iloc[3]
ge99cw.reindex(ge99cw.index.drop(3))

3,ST_CODE,ST_NAME,PC_NO,PC_NAME,PC_TYPE,MONTH,YEAR,CAND_NAME,CAND_SEX,PARTYABBRE,TOTVOTPOLL,POSITION
0,GENERAL ELECTION 1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CANDIDATE WISE RESULT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Yerrannaidu Kinjarapu,M,TDP,373851,1
5,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Kanithi Viswanadaham,M,INC,276969,2
6,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Appala Naidu Golive,M,AJBP,7280,3
7,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Dadichiluka Veera Gouri Sankara Rao,M,TDP,304000,1
8,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Kishore Chandra Suryanarayana Deo Vyricherla,M,INC,290719,2
9,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Arika Gumpa Swamy,M,IND,9750,3
10,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Vooyaka Mutyalu,M,IND,9172,4
11,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Botcha Satyanarayana,M,INC,339768,1
12,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Aruna Padala,F,TDP,335947,2
13,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Manjula Dasari,F,AJBP,16425,3
14,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Enumula Appa Rao,M,IND,2010,4
15,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,M.V.V.S.Murthy,M,TDP,442036,1
16,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,T.Subbarami Reddy,M,INC,403117,2
17,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Ch.Narsinga Rao,M,CPM,26610,3
18,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Navish Yadav(T.N.V.Murthi B.E.),M,SP,9377,4
19,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Appa Rao Gudivada,M,IND,2263,5
20,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Nanduri Pani,M,IND,1458,6
21,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Dumpa Mary Vijaya Kumari,F,TDP,293593,1
22,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,T.Ratnabai,F,INC,256490,2
23,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Ramaiah Sode,M,CPI,122496,3
24,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Pangi Satyanarayana,M,NTRTDP(LP),24425,4
25,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,K. Ranga Reddy,M,IND,16893,5
26,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Kurasam Subba Rao,M,IND,14659,6
27,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Ganta Srinivasa Rao,M,TDP,392984,1
28,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Gurunadha Rao Gudivada,M,INC,334520,2
29,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Appala Trinadha Rao Bheesetti,M,ATDP,13918,3
30,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Choday Srinivasa Rao,M,NTRTDP(LP),3562,4
...,...,...,...,...,...,...,...,...,...,...,...,...
4622,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Ravi,M,IND,232,9
4623,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Kumar Sen Bouddh,M,IND,225,10
4624,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Sanjeev Vaid,M,NCY,179,11
4625,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Narender Sharma,M,IND,155,12
4626,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Mankeshwar Nath,M,IND,148,13
4627,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Anita Arya,F,BJP,128956,1
4628,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Meira Kumar,F,INC,116502,2
4629,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ram Swaroop,M,BSP,5662,3
4630,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Vinod Kumar,M,IND,2005,4
4631,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lala Ram,M,IND,1496,5
4632,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ganga Sahay Bhirava,M,NCP,1398,6
4633,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kalawati,F,BPM,508,7
4634,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Mohinder Singh,M,IND,479,8
4635,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lalit Kumar Sakkarwal,M,IND,444,9
4636,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Shailendra,M,ABMAD,368,10
4637,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kusum Lata,F,IND,289,11
4638,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Babu Lal Tory,M,IND,186,12
4639,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,P.M. Sayeed,M,INC,16113,1
4640,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Dr. K.P. Muthukoya,M,JD(U),12924,2
4641,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Hussain Faburikage,M,JD(S),542,3
4642,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Ameer Biyyammada,M,IND,281,4
4643,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M O H Farook,M,INC,165108,1
4644,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M Ramadass,M,PMK,140920,2
4645,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,P Kannan,M,TMC(M),111737,3
4646,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Kalivaradhan,M,IND,9452,4
4647,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,A Ramalingam,M,IND,5562,5
4648,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Adv. T Ashok Kumar,M,IND,5179,6
4649,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Dr. K Padmarajan,M,IND,2700,7
4650,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,S Paramasivam,M,IND,2155,8
4651,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Surendra Kumar Gupta,M,IND,1349,9

In [80]:
ge99cw.drop(0, inplace = True)
ge99cw.drop(1, inplace = True)
ge99cw.drop(2, inplace = True)
ge99cw.drop(3, inplace = True)

In [81]:
ge99cw.reset_index(inplace=True)

In [82]:
del ge99cw['index']

In [83]:
 ge99cw

3,ST_CODE,ST_NAME,PC_NO,PC_NAME,PC_TYPE,MONTH,YEAR,CAND_NAME,CAND_SEX,PARTYABBRE,TOTVOTPOLL,POSITION
0,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Yerrannaidu Kinjarapu,M,TDP,373851,1
1,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Kanithi Viswanadaham,M,INC,276969,2
2,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Appala Naidu Golive,M,AJBP,7280,3
3,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Dadichiluka Veera Gouri Sankara Rao,M,TDP,304000,1
4,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Kishore Chandra Suryanarayana Deo Vyricherla,M,INC,290719,2
5,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Arika Gumpa Swamy,M,IND,9750,3
6,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Vooyaka Mutyalu,M,IND,9172,4
7,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Botcha Satyanarayana,M,INC,339768,1
8,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Aruna Padala,F,TDP,335947,2
9,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Manjula Dasari,F,AJBP,16425,3
10,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Enumula Appa Rao,M,IND,2010,4
11,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,M.V.V.S.Murthy,M,TDP,442036,1
12,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,T.Subbarami Reddy,M,INC,403117,2
13,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Ch.Narsinga Rao,M,CPM,26610,3
14,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Navish Yadav(T.N.V.Murthi B.E.),M,SP,9377,4
15,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Appa Rao Gudivada,M,IND,2263,5
16,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Nanduri Pani,M,IND,1458,6
17,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Dumpa Mary Vijaya Kumari,F,TDP,293593,1
18,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,T.Ratnabai,F,INC,256490,2
19,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Ramaiah Sode,M,CPI,122496,3
20,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Pangi Satyanarayana,M,NTRTDP(LP),24425,4
21,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,K. Ranga Reddy,M,IND,16893,5
22,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Kurasam Subba Rao,M,IND,14659,6
23,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Ganta Srinivasa Rao,M,TDP,392984,1
24,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Gurunadha Rao Gudivada,M,INC,334520,2
25,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Appala Trinadha Rao Bheesetti,M,ATDP,13918,3
26,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Choday Srinivasa Rao,M,NTRTDP(LP),3562,4
27,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Mudragada Padmanabham,M,TDP,435811,1
28,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Thota Subbarao,M,INC,314376,2
29,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Boddu Krishna Mohan,M,ATDP,44466,3
...,...,...,...,...,...,...,...,...,...,...,...,...
4618,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Ravi,M,IND,232,9
4619,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Kumar Sen Bouddh,M,IND,225,10
4620,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Sanjeev Vaid,M,NCY,179,11
4621,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Narender Sharma,M,IND,155,12
4622,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Mankeshwar Nath,M,IND,148,13
4623,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Anita Arya,F,BJP,128956,1
4624,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Meira Kumar,F,INC,116502,2
4625,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ram Swaroop,M,BSP,5662,3
4626,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Vinod Kumar,M,IND,2005,4
4627,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lala Ram,M,IND,1496,5
4628,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ganga Sahay Bhirava,M,NCP,1398,6
4629,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kalawati,F,BPM,508,7
4630,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Mohinder Singh,M,IND,479,8
4631,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lalit Kumar Sakkarwal,M,IND,444,9
4632,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Shailendra,M,ABMAD,368,10
4633,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kusum Lata,F,IND,289,11
4634,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Babu Lal Tory,M,IND,186,12
4635,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,P.M. Sayeed,M,INC,16113,1
4636,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Dr. K.P. Muthukoya,M,JD(U),12924,2
4637,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Hussain Faburikage,M,JD(S),542,3
4638,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Ameer Biyyammada,M,IND,281,4
4639,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M O H Farook,M,INC,165108,1
4640,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M Ramadass,M,PMK,140920,2
4641,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,P Kannan,M,TMC(M),111737,3
4642,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Kalivaradhan,M,IND,9452,4
4643,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,A Ramalingam,M,IND,5562,5
4644,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Adv. T Ashok Kumar,M,IND,5179,6
4645,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Dr. K Padmarajan,M,IND,2700,7
4646,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,S Paramasivam,M,IND,2155,8
4647,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Surendra Kumar Gupta,M,IND,1349,9

In [84]:
ge99cw.to_csv('CW1999.csv',index=False)

In [85]:
cw=pd.read_csv('CW1999.csv')

In [86]:
cw

,ST_CODE,ST_NAME,PC_NO,PC_NAME,PC_TYPE,MONTH,YEAR,CAND_NAME,CAND_SEX,PARTYABBRE,TOTVOTPOLL,POSITION
0,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Yerrannaidu Kinjarapu,M,TDP,373851,1
1,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Kanithi Viswanadaham,M,INC,276969,2
2,S01,ANDHRA PRADESH,1,Srikakulam,GEN,7,1999,Appala Naidu Golive,M,AJBP,7280,3
3,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Dadichiluka Veera Gouri Sankara Rao,M,TDP,304000,1
4,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Kishore Chandra Suryanarayana Deo Vyricherla,M,INC,290719,2
5,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Arika Gumpa Swamy,M,IND,9750,3
6,S01,ANDHRA PRADESH,2,Parvathipuram,ST,7,1999,Vooyaka Mutyalu,M,IND,9172,4
7,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Botcha Satyanarayana,M,INC,339768,1
8,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Aruna Padala,F,TDP,335947,2
9,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Manjula Dasari,F,AJBP,16425,3
10,S01,ANDHRA PRADESH,3,Bobbili,GEN,7,1999,Enumula Appa Rao,M,IND,2010,4
11,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,M.V.V.S.Murthy,M,TDP,442036,1
12,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,T.Subbarami Reddy,M,INC,403117,2
13,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Ch.Narsinga Rao,M,CPM,26610,3
14,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Navish Yadav(T.N.V.Murthi B.E.),M,SP,9377,4
15,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Appa Rao Gudivada,M,IND,2263,5
16,S01,ANDHRA PRADESH,4,Visakhapatnam,GEN,7,1999,Nanduri Pani,M,IND,1458,6
17,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Dumpa Mary Vijaya Kumari,F,TDP,293593,1
18,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,T.Ratnabai,F,INC,256490,2
19,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Ramaiah Sode,M,CPI,122496,3
20,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Pangi Satyanarayana,M,NTRTDP(LP),24425,4
21,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,K. Ranga Reddy,M,IND,16893,5
22,S01,ANDHRA PRADESH,5,Bhadrachalam,ST,7,1999,Kurasam Subba Rao,M,IND,14659,6
23,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Ganta Srinivasa Rao,M,TDP,392984,1
24,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Gurunadha Rao Gudivada,M,INC,334520,2
25,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Appala Trinadha Rao Bheesetti,M,ATDP,13918,3
26,S01,ANDHRA PRADESH,6,Anakapalli,GEN,7,1999,Choday Srinivasa Rao,M,NTRTDP(LP),3562,4
27,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Mudragada Padmanabham,M,TDP,435811,1
28,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Thota Subbarao,M,INC,314376,2
29,S01,ANDHRA PRADESH,7,Kakinada,GEN,7,1999,Boddu Krishna Mohan,M,ATDP,44466,3
...,...,...,...,...,...,...,...,...,...,...,...,...
4618,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Ravi,M,IND,232,9
4619,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Kumar Sen Bouddh,M,IND,225,10
4620,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Sanjeev Vaid,M,NCY,179,11
4621,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Narender Sharma,M,IND,155,12
4622,U05,NATIONAL CAPITAL TERRITORY OF DELHI,6,Delhi Sadar,GEN,7,1999,Mankeshwar Nath,M,IND,148,13
4623,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Anita Arya,F,BJP,128956,1
4624,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Meira Kumar,F,INC,116502,2
4625,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ram Swaroop,M,BSP,5662,3
4626,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Vinod Kumar,M,IND,2005,4
4627,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lala Ram,M,IND,1496,5
4628,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Ganga Sahay Bhirava,M,NCP,1398,6
4629,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kalawati,F,BPM,508,7
4630,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Mohinder Singh,M,IND,479,8
4631,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Lalit Kumar Sakkarwal,M,IND,444,9
4632,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Shailendra,M,ABMAD,368,10
4633,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Kusum Lata,F,IND,289,11
4634,U05,NATIONAL CAPITAL TERRITORY OF DELHI,7,Karol Bagh,SC,7,1999,Babu Lal Tory,M,IND,186,12
4635,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,P.M. Sayeed,M,INC,16113,1
4636,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Dr. K.P. Muthukoya,M,JD(U),12924,2
4637,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Hussain Faburikage,M,JD(S),542,3
4638,U06,LAKSHADWEEP,1,Lakshadweep,ST,7,1999,Ameer Biyyammada,M,IND,281,4
4639,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M O H Farook,M,INC,165108,1
4640,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,M Ramadass,M,PMK,140920,2
4641,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,P Kannan,M,TMC(M),111737,3
4642,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Kalivaradhan,M,IND,9452,4
4643,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,A Ramalingam,M,IND,5562,5
4644,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Adv. T Ashok Kumar,M,IND,5179,6
4645,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Dr. K Padmarajan,M,IND,2700,7
4646,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,S Paramasivam,M,IND,2155,8
4647,U07,PONDICHERRY,1,Pondicherry,GEN,7,1999,Surendra Kumar Gupta,M,IND,1349,9

In [87]:
 age = cw.pivot_table(values=['TOTVOTPOLL'],index=['ST_NAME'],columns=['CAND_SEX'], aggfunc=len)

In [88]:
age

                                    TOTVOTPOLL
CAND_SEX                                     F       M
ST_NAME
ANDAMAN & NICOBAR ISLANDS                  1.0     4.0
ANDHRA PRADESH                            18.0   267.0
ARUNACHAL PRADESH                          NaN     6.0
ASSAM                                      9.0   106.0
BIHAR                                     20.0   477.0
CHANDIGARH                                 3.0    13.0
DADRA & NAGAR HAVELI                       NaN     5.0
DAMAN & DIU                                NaN     4.0
GOA                                        1.0    15.0
GUJARAT                                    8.0   151.0
HARYANA                                    3.0   111.0
HIMACHAL PRADESH                           1.0    21.0
JAMMU & KASHMIR                            6.0    77.0
KARNATAKA                                 11.0   119.0
KERALA                                    13.0   129.0
LAKSHADWEEP                                NaN     4.0
MADHYA PRADESH                            23.0   321.0
MAHARASHTRA                               17.0   244.0
MANIPUR                                    2.0    16.0
MEGHALAYA                                  NaN    14.0
MIZORAM                                    NaN     7.0
NAGALAND                                   NaN     5.0
NATIONAL CAPITAL TERRITORY OF DELHI        7.0    90.0
ORISSA                                     8.0    97.0
PONDICHERRY                                NaN     9.0
PUNJAB                                    14.0   106.0
RAJASTHAN                                 15.0   150.0
SIKKIM                                     NaN     4.0
TAMIL NADU                                17.0   345.0
TRIPURA                                    NaN    17.0
UTTAR PRADESH                             61.0  1147.0
WEST BENGAL                               26.0   283.0

In [89]:
a=age['TOTVOTPOLL','F']
b=age['TOTVOTPOLL','M']

In [90]:
def gcd(a,b):
    if b>a:
        while b > 0:
            a, b = b, a % b
        return a
    elif a>b:
        while a > 0:
            b, a = a, b % a
        return b
    else:
        return 1

In [91]:
age.reset_index(inplace=True)

In [92]:
age.fillna(value=0)

                                      ST_NAME TOTVOTPOLL
CAND_SEX                                               F       M
0                   ANDAMAN & NICOBAR ISLANDS        1.0     4.0
1                              ANDHRA PRADESH       18.0   267.0
2                           ARUNACHAL PRADESH        0.0     6.0
3                                       ASSAM        9.0   106.0
4                                       BIHAR       20.0   477.0
5                                  CHANDIGARH        3.0    13.0
6                        DADRA & NAGAR HAVELI        0.0     5.0
7                                 DAMAN & DIU        0.0     4.0
8                                         GOA        1.0    15.0
9                                     GUJARAT        8.0   151.0
10                                    HARYANA        3.0   111.0
11                           HIMACHAL PRADESH        1.0    21.0
12                            JAMMU & KASHMIR        6.0    77.0
13                                  KARNATAKA       11.0   119.0
14                                     KERALA       13.0   129.0
15                                LAKSHADWEEP        0.0     4.0
16                             MADHYA PRADESH       23.0   321.0
17                                MAHARASHTRA       17.0   244.0
18                                    MANIPUR        2.0    16.0
19                                  MEGHALAYA        0.0    14.0
20                                    MIZORAM        0.0     7.0
21                                   NAGALAND        0.0     5.0
22        NATIONAL CAPITAL TERRITORY OF DELHI        7.0    90.0
23                                     ORISSA        8.0    97.0
24                                PONDICHERRY        0.0     9.0
25                                     PUNJAB       14.0   106.0
26                                  RAJASTHAN       15.0   150.0
27                                     SIKKIM        0.0     4.0
28                                 TAMIL NADU       17.0   345.0
29                                    TRIPURA        0.0    17.0
30                              UTTAR PRADESH       61.0  1147.0
31                                WEST BENGAL       26.0   283.0

In [93]:
age.columns = age.columns.get_level_values(1)

In [94]:
ca = list(age.columns)

In [95]:
ca[0]='STATE'

In [96]:
age.columns = ca

In [97]:
age

                                  STATE     F       M
0             ANDAMAN & NICOBAR ISLANDS   1.0     4.0
1                        ANDHRA PRADESH  18.0   267.0
2                     ARUNACHAL PRADESH   NaN     6.0
3                                 ASSAM   9.0   106.0
4                                 BIHAR  20.0   477.0
5                            CHANDIGARH   3.0    13.0
6                  DADRA & NAGAR HAVELI   NaN     5.0
7                           DAMAN & DIU   NaN     4.0
8                                   GOA   1.0    15.0
9                               GUJARAT   8.0   151.0
10                              HARYANA   3.0   111.0
11                     HIMACHAL PRADESH   1.0    21.0
12                      JAMMU & KASHMIR   6.0    77.0
13                            KARNATAKA  11.0   119.0
14                               KERALA  13.0   129.0
15                          LAKSHADWEEP   NaN     4.0
16                       MADHYA PRADESH  23.0   321.0
17                          MAHARASHTRA  17.0   244.0
18                              MANIPUR   2.0    16.0
19                            MEGHALAYA   NaN    14.0
20                              MIZORAM   NaN     7.0
21                             NAGALAND   NaN     5.0
22  NATIONAL CAPITAL TERRITORY OF DELHI   7.0    90.0
23                               ORISSA   8.0    97.0
24                          PONDICHERRY   NaN     9.0
25                               PUNJAB  14.0   106.0
26                            RAJASTHAN  15.0   150.0
27                               SIKKIM   NaN     4.0
28                           TAMIL NADU  17.0   345.0
29                              TRIPURA   NaN    17.0
30                        UTTAR PRADESH  61.0  1147.0
31                          WEST BENGAL  26.0   283.0

In [98]:
x = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in age.index:
    x[i] = gcd(a[i],b[i])

In [99]:
f=a/x.copy()
m=b/x.copy()

In [100]:
f=pd.Series.to_frame(f)
f.reset_index(inplace=True)

In [101]:
m=pd.Series.to_frame(m)
m.reset_index(inplace=True)

In [102]:
m.columns = m.columns.get_level_values(1)

In [103]:
ck = list(m.columns)

In [104]:
ck[0]='STATE'
ck[1]='Male_Candidates'

In [105]:
m.columns= ck

In [106]:
m

                                  STATE  Male_Candidates
0             ANDAMAN & NICOBAR ISLANDS              4.0
1                        ANDHRA PRADESH             89.0
2                     ARUNACHAL PRADESH              6.0
3                                 ASSAM            106.0
4                                 BIHAR            477.0
5                            CHANDIGARH             13.0
6                  DADRA & NAGAR HAVELI              5.0
7                           DAMAN & DIU              4.0
8                                   GOA             15.0
9                               GUJARAT            151.0
10                              HARYANA             37.0
11                     HIMACHAL PRADESH             21.0
12                      JAMMU & KASHMIR             77.0
13                            KARNATAKA            119.0
14                               KERALA            129.0
15                          LAKSHADWEEP              4.0
16                       MADHYA PRADESH            321.0
17                          MAHARASHTRA            244.0
18                              MANIPUR              8.0
19                            MEGHALAYA             14.0
20                              MIZORAM              7.0
21                             NAGALAND              5.0
22  NATIONAL CAPITAL TERRITORY OF DELHI             90.0
23                               ORISSA             97.0
24                          PONDICHERRY              9.0
25                               PUNJAB             53.0
26                            RAJASTHAN             10.0
27                               SIKKIM              4.0
28                           TAMIL NADU            345.0
29                              TRIPURA             17.0
30                        UTTAR PRADESH           1147.0
31                          WEST BENGAL            283.0

In [107]:
f.columns = f.columns.get_level_values(1)

In [108]:
cl = list(f.columns)

In [109]:
cl[0]='STATE'
cl[1]='Female_Candidates'

In [110]:
f.columns= cl

In [111]:
o=pd.merge(age,f,on='STATE')

In [112]:
oge=pd.merge(o,m,on='STATE')

In [113]:
oge.fillna(value=0,inplace=True)

In [114]:
oge

,STATE,F,M,Female_Candidates,Male_Candidates
0,ANDAMAN & NICOBAR ISLANDS,1.0,4.0,1.0,4.0
1,ANDHRA PRADESH,18.0,267.0,6.0,89.0
2,ARUNACHAL PRADESH,0.0,6.0,0.0,6.0
3,ASSAM,9.0,106.0,9.0,106.0
4,BIHAR,20.0,477.0,20.0,477.0
5,CHANDIGARH,3.0,13.0,3.0,13.0
6,DADRA & NAGAR HAVELI,0.0,5.0,0.0,5.0
7,DAMAN & DIU,0.0,4.0,0.0,4.0
8,GOA,1.0,15.0,1.0,15.0
9,GUJARAT,8.0,151.0,8.0,151.0
10,HARYANA,3.0,111.0,1.0,37.0
11,HIMACHAL PRADESH,1.0,21.0,1.0,21.0
12,JAMMU & KASHMIR,6.0,77.0,6.0,77.0
13,KARNATAKA,11.0,119.0,11.0,119.0
14,KERALA,13.0,129.0,13.0,129.0
15,LAKSHADWEEP,0.0,4.0,0.0,4.0
16,MADHYA PRADESH,23.0,321.0,23.0,321.0
17,MAHARASHTRA,17.0,244.0,17.0,244.0
18,MANIPUR,2.0,16.0,1.0,8.0
19,MEGHALAYA,0.0,14.0,0.0,14.0
20,MIZORAM,0.0,7.0,0.0,7.0
21,NAGALAND,0.0,5.0,0.0,5.0
22,NATIONAL CAPITAL TERRITORY OF DELHI,7.0,90.0,7.0,90.0
23,ORISSA,8.0,97.0,8.0,97.0
24,PONDICHERRY,0.0,9.0,0.0,9.0
25,PUNJAB,14.0,106.0,7.0,53.0
26,RAJASTHAN,15.0,150.0,1.0,10.0
27,SIKKIM,0.0,4.0,0.0,4.0
28,TAMIL NADU,17.0,345.0,17.0,345.0
29,TRIPURA,0.0,17.0,0.0,17.0
30,UTTAR PRADESH,61.0,1147.0,61.0,1147.0
31,WEST BENGAL,26.0,283.0,26.0,283.0

In [115]:
oge['FtoM_ratio'] = oge['Female_Candidates'].astype(str).str.cat(oge['Male_Candidates'].astype(str), sep=' : ')

In [116]:
oge

,STATE,F,M,Female_Candidates,Male_Candidates,FtoM_ratio
0,ANDAMAN & NICOBAR ISLANDS,1.0,4.0,1.0,4.0,1.0 : 4.0
1,ANDHRA PRADESH,18.0,267.0,6.0,89.0,6.0 : 89.0
2,ARUNACHAL PRADESH,0.0,6.0,0.0,6.0,0.0 : 6.0
3,ASSAM,9.0,106.0,9.0,106.0,9.0 : 106.0
4,BIHAR,20.0,477.0,20.0,477.0,20.0 : 477.0
5,CHANDIGARH,3.0,13.0,3.0,13.0,3.0 : 13.0
6,DADRA & NAGAR HAVELI,0.0,5.0,0.0,5.0,0.0 : 5.0
7,DAMAN & DIU,0.0,4.0,0.0,4.0,0.0 : 4.0
8,GOA,1.0,15.0,1.0,15.0,1.0 : 15.0
9,GUJARAT,8.0,151.0,8.0,151.0,8.0 : 151.0
10,HARYANA,3.0,111.0,1.0,37.0,1.0 : 37.0
11,HIMACHAL PRADESH,1.0,21.0,1.0,21.0,1.0 : 21.0
12,JAMMU & KASHMIR,6.0,77.0,6.0,77.0,6.0 : 77.0
13,KARNATAKA,11.0,119.0,11.0,119.0,11.0 : 119.0
14,KERALA,13.0,129.0,13.0,129.0,13.0 : 129.0
15,LAKSHADWEEP,0.0,4.0,0.0,4.0,0.0 : 4.0
16,MADHYA PRADESH,23.0,321.0,23.0,321.0,23.0 : 321.0
17,MAHARASHTRA,17.0,244.0,17.0,244.0,17.0 : 244.0
18,MANIPUR,2.0,16.0,1.0,8.0,1.0 : 8.0
19,MEGHALAYA,0.0,14.0,0.0,14.0,0.0 : 14.0
20,MIZORAM,0.0,7.0,0.0,7.0,0.0 : 7.0
21,NAGALAND,0.0,5.0,0.0,5.0,0.0 : 5.0
22,NATIONAL CAPITAL TERRITORY OF DELHI,7.0,90.0,7.0,90.0,7.0 : 90.0
23,ORISSA,8.0,97.0,8.0,97.0,8.0 : 97.0
24,PONDICHERRY,0.0,9.0,0.0,9.0,0.0 : 9.0
25,PUNJAB,14.0,106.0,7.0,53.0,7.0 : 53.0
26,RAJASTHAN,15.0,150.0,1.0,10.0,1.0 : 10.0
27,SIKKIM,0.0,4.0,0.0,4.0,0.0 : 4.0
28,TAMIL NADU,17.0,345.0,17.0,345.0,17.0 : 345.0
29,TRIPURA,0.0,17.0,0.0,17.0,0.0 : 17.0
30,UTTAR PRADESH,61.0,1147.0,61.0,1147.0,61.0 : 1147.0
31,WEST BENGAL,26.0,283.0,26.0,283.0,26.0 : 283.0

In [117]:
del oge['Female_Candidates']

In [118]:
del oge['Male_Candidates']

In [66]:
oge

                                  STATE     F       M     FtoM_ratio
0             ANDAMAN & NICOBAR ISLANDS   1.0     4.0      1.0 : 4.0
1                        ANDHRA PRADESH  18.0   267.0     6.0 : 89.0
2                     ARUNACHAL PRADESH   0.0     6.0      0.0 : 6.0
3                                 ASSAM   9.0   106.0    9.0 : 106.0
4                                 BIHAR  20.0   477.0   20.0 : 477.0
5                            CHANDIGARH   3.0    13.0     3.0 : 13.0
6                  DADRA & NAGAR HAVELI   0.0     5.0      0.0 : 5.0
7                           DAMAN & DIU   0.0     4.0      0.0 : 4.0
8                                   GOA   1.0    15.0     1.0 : 15.0
9                               GUJARAT   8.0   151.0    8.0 : 151.0
10                              HARYANA   3.0   111.0     1.0 : 37.0
11                     HIMACHAL PRADESH   1.0    21.0     1.0 : 21.0
12                      JAMMU & KASHMIR   6.0    77.0     6.0 : 77.0
13                            KARNATAKA  11.0   119.0   11.0 : 119.0
14                               KERALA  13.0   129.0   13.0 : 129.0
15                          LAKSHADWEEP   0.0     4.0      0.0 : 4.0
16                       MADHYA PRADESH  23.0   321.0   23.0 : 321.0
17                          MAHARASHTRA  17.0   244.0   17.0 : 244.0
18                              MANIPUR   2.0    16.0      1.0 : 8.0
19                            MEGHALAYA   0.0    14.0     0.0 : 14.0
20                              MIZORAM   0.0     7.0      0.0 : 7.0
21                             NAGALAND   0.0     5.0      0.0 : 5.0
22  NATIONAL CAPITAL TERRITORY OF DELHI   7.0    90.0     7.0 : 90.0
23                               ORISSA   8.0    97.0     8.0 : 97.0
24                          PONDICHERRY   0.0     9.0      0.0 : 9.0
25                               PUNJAB  14.0   106.0     7.0 : 53.0
26                            RAJASTHAN  15.0   150.0     1.0 : 10.0
27                               SIKKIM   0.0     4.0      0.0 : 4.0
28                           TAMIL NADU  17.0   345.0   17.0 : 345.0
29                              TRIPURA   0.0    17.0     0.0 : 17.0
30                        UTTAR PRADESH  61.0  1147.0  61.0 : 1147.0
31                          WEST BENGAL  26.0   283.0   26.0 : 283.0

In [119]:
s1999.reset_index(inplace=True)

In [121]:
s1999.to_csv('s1999.csv',index=False)

In [124]:
s1999=pd.read_csv('s1999.csv')

In [126]:
s1999.rename(columns={'ST_NAME':'STATE'},inplace=True)

In [127]:
s1999

,STATE,TOT_CONTESTANT,TOT_ELECTORS,TOT_VOTERS,POLL_PERC in %
0,ANDAMAN & NICOBAR ISLANDS,5,247384,147102,59.463021
1,ANDHRA PRADESH,285,49654389,34332073,69.142071
2,ARUNACHAL PRADESH,6,611572,441231,72.147024
3,ASSAM,115,14290673,10182919,71.255699
4,BIHAR,497,58788098,36143272,61.480594
5,CHANDIGARH,16,585006,282879,48.354889
6,DADRA & NAGAR HAVELI,5,98376,73507,74.720460
7,DAMAN & DIU,4,72216,51811,71.744489
8,GOA,16,908849,409944,45.105843
9,GUJARAT,159,29512402,13878611,47.026369
10,HARYANA,114,11038955,7029964,63.683238
11,HIMACHAL PRADESH,22,3786479,2149816,56.776124
12,JAMMU & KASHMIR,83,5030094,1626945,32.344227
13,KARNATAKA,130,34284098,23168337,67.577502
14,KERALA,142,22058901,15482676,70.187885
15,LAKSHADWEEP,4,37619,30174,80.209469
16,MADHYA PRADESH,344,46915473,25746824,54.879174
17,MAHARASHTRA,261,56853196,34660007,60.964043
18,MANIPUR,18,1372339,901242,65.671966
19,MEGHALAYA,14,1178250,661657,56.155909
20,MIZORAM,7,449406,293513,65.311322
21,NAGALAND,5,955914,728843,76.245666
22,NATIONAL CAPITAL TERRITORY OF DELHI,97,8712530,3793697,43.543001
23,ORISSA,105,24187490,13456534,55.634272
24,PONDICHERRY,9,701990,444174,63.273551
25,PUNJAB,120,15717304,8819200,56.111404
26,RAJASTHAN,165,31106488,16754016,53.860198
27,SIKKIM,4,255377,208670,81.710569
28,TAMIL NADU,362,47733664,27676543,57.981183
29,TRIPURA,17,1796055,1223784,68.137334
30,UTTAR PRADESH,1208,102946404,55107957,53.530726
31,WEST BENGAL,309,47649856,35761182,75.049927

In [128]:
output = pd.merge(s1999,oge,on='STATE')

In [129]:
output

,STATE,TOT_CONTESTANT,TOT_ELECTORS,TOT_VOTERS,POLL_PERC in %,F,M,FtoM_ratio
0,ANDAMAN & NICOBAR ISLANDS,5,247384,147102,59.463021,1.0,4.0,1.0 : 4.0
1,ANDHRA PRADESH,285,49654389,34332073,69.142071,18.0,267.0,6.0 : 89.0
2,ARUNACHAL PRADESH,6,611572,441231,72.147024,0.0,6.0,0.0 : 6.0
3,ASSAM,115,14290673,10182919,71.255699,9.0,106.0,9.0 : 106.0
4,BIHAR,497,58788098,36143272,61.480594,20.0,477.0,20.0 : 477.0
5,CHANDIGARH,16,585006,282879,48.354889,3.0,13.0,3.0 : 13.0
6,DADRA & NAGAR HAVELI,5,98376,73507,74.720460,0.0,5.0,0.0 : 5.0
7,DAMAN & DIU,4,72216,51811,71.744489,0.0,4.0,0.0 : 4.0
8,GOA,16,908849,409944,45.105843,1.0,15.0,1.0 : 15.0
9,GUJARAT,159,29512402,13878611,47.026369,8.0,151.0,8.0 : 151.0
10,HARYANA,114,11038955,7029964,63.683238,3.0,111.0,1.0 : 37.0
11,HIMACHAL PRADESH,22,3786479,2149816,56.776124,1.0,21.0,1.0 : 21.0
12,JAMMU & KASHMIR,83,5030094,1626945,32.344227,6.0,77.0,6.0 : 77.0
13,KARNATAKA,130,34284098,23168337,67.577502,11.0,119.0,11.0 : 119.0
14,KERALA,142,22058901,15482676,70.187885,13.0,129.0,13.0 : 129.0
15,LAKSHADWEEP,4,37619,30174,80.209469,0.0,4.0,0.0 : 4.0
16,MADHYA PRADESH,344,46915473,25746824,54.879174,23.0,321.0,23.0 : 321.0
17,MAHARASHTRA,261,56853196,34660007,60.964043,17.0,244.0,17.0 : 244.0
18,MANIPUR,18,1372339,901242,65.671966,2.0,16.0,1.0 : 8.0
19,MEGHALAYA,14,1178250,661657,56.155909,0.0,14.0,0.0 : 14.0
20,MIZORAM,7,449406,293513,65.311322,0.0,7.0,0.0 : 7.0
21,NAGALAND,5,955914,728843,76.245666,0.0,5.0,0.0 : 5.0
22,NATIONAL CAPITAL TERRITORY OF DELHI,97,8712530,3793697,43.543001,7.0,90.0,7.0 : 90.0
23,ORISSA,105,24187490,13456534,55.634272,8.0,97.0,8.0 : 97.0
24,PONDICHERRY,9,701990,444174,63.273551,0.0,9.0,0.0 : 9.0
25,PUNJAB,120,15717304,8819200,56.111404,14.0,106.0,7.0 : 53.0
26,RAJASTHAN,165,31106488,16754016,53.860198,15.0,150.0,1.0 : 10.0
27,SIKKIM,4,255377,208670,81.710569,0.0,4.0,0.0 : 4.0
28,TAMIL NADU,362,47733664,27676543,57.981183,17.0,345.0,17.0 : 345.0
29,TRIPURA,17,1796055,1223784,68.137334,0.0,17.0,0.0 : 17.0
30,UTTAR PRADESH,1208,102946404,55107957,53.530726,61.0,1147.0,61.0 : 1147.0
31,WEST BENGAL,309,47649856,35761182,75.049927,26.0,283.0,26.0 : 283.0

In [130]:
output.to_csv('GE1999_detail.csv',index=False)

In [132]:
g=cw[cw['POSITION']==1].copy()

In [135]:
pp=g.pivot_table(index=['ST_NAME','PARTYABBRE'],values='TOTVOTPOLL', aggfunc=len).copy()

In [171]:
g['CAND_SEX'].value_counts()

M    494
F     49
Name: CAND_SEX, dtype: int64

In [172]:
qw = pd.DataFrame(g['CAND_SEX'].value_counts())

In [173]:
qw.reset_index(inplace=True)

In [174]:
qw

  index  CAND_SEX
0     M       494
1     F        49

In [175]:
qw.rename(columns={'index':'Indicators','CAND_SEX':'Election 1999'},inplace=True)

In [176]:
qw['Indicators'][0]= 'Male in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [177]:
qw['Indicators'][1]= 'Female in LowerHouse'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [178]:
qw

             Indicators  Election 1999
0    Male in LowerHouse            494
1  Female in LowerHouse             49

In [179]:
ind = pd.DataFrame(g['PARTYABBRE'].describe())

In [180]:
ind

       PARTYABBRE
count         543
unique         39
top           BJP
freq          182

In [181]:
ind.reset_index(inplace=True)

In [182]:
ind.rename(columns={'index':'Indicators','PARTYABBRE':'Election 1999'},inplace=True)

In [183]:
ind

  Indicators Election 1999
0      count           543
1     unique            39
2        top           BJP
3       freq           182

In [184]:
ind['Indicators'][0]= 'Total seats contested for'
ind['Indicators'][1]= 'Number of Parties'

In [185]:
ind['Indicators'][2]= 'Party with majority'
ind['Indicators'][3]= 'Majority party eats won'

In [186]:
ind

                  Indicators Election 1999
0  Total seats contested for           543
1          Number of Parties            39
2        Party with majority           BJP
3    Majority party eats won           182

In [187]:
eld = pd.read_csv('ecyw.csv')

In [188]:
todisplay=eld[['Indicators','Election 1999']].copy()

In [189]:
todisplay

                                          Indicators  Election 1999
0   India's Real GDP Growth Rates\r\r\n(Factor Cost)       5.347500
1                             Agriculture growth (%)       2.112500
2                                Industry growth (%)       5.792500
3                                Services growth (%)       6.577500
4                                   By Demand (%YoY)            NaN
5                                        Consumption       4.000000
6                                Private Consumption       4.550000
7                                 Public Consumption       1.350000
8                      Gross Fixed Capital Formation       6.950000
9           Consumption; Investments, Savings (%GDP)            NaN
10                                       Consumption      77.400000
11                                 Capital Formation      24.400000
12                            Gross Domestic Savings      24.975000
13                                      Money Supply      15.300000
14                                Bank Credit growth      19.375000
15                                    Deposit growth      16.300000
16                         Fiscal Indicators (% GDP)            NaN
17                           Centre's Fiscal Deficit      -5.333333
18                              State Fiscal Deficit      -3.666667
19                   Combined Deficit (Centre+State)      -9.000000
20                         Inflation - WPI (Average)       4.900000
21                                     CPI (Average)       3.975000
22                                   Exports (US$bn)      52.575000
23                                             % YoY      15.732500
24                                   Imports (US$bn)      64.675000
25                                              %YoY      10.107500
26                             Trade deficit (US$bn)     -12.125000
27                                Invisibles (US$bn)      17.400000
28                   Current Account Deficit (US$bn)       5.275000
29                                          % to GDP       0.900000
30                           Capital Account (US$bn)      11.225000
31                                             % GDP       2.100000
32                   Forex Assets (exc. gold)(US$bn)      80.600000
33                             External Debt (US$bn)     104.425000
34                                   Short Term Debt       3.850000
35                       Exchange Rate US$/Rs. -avg.      46.925000

In [190]:
col1=pd.concat([todisplay,qw,ind]).reset_index()

In [191]:
del col1['index']

In [192]:
col1

                                          Indicators Election 1999
0   India's Real GDP Growth Rates\r\r\n(Factor Cost)        5.3475
1                             Agriculture growth (%)        2.1125
2                                Industry growth (%)        5.7925
3                                Services growth (%)        6.5775
4                                   By Demand (%YoY)           NaN
5                                        Consumption             4
6                                Private Consumption          4.55
7                                 Public Consumption          1.35
8                      Gross Fixed Capital Formation          6.95
9           Consumption; Investments, Savings (%GDP)           NaN
10                                       Consumption          77.4
11                                 Capital Formation          24.4
12                            Gross Domestic Savings        24.975
13                                      Money Supply          15.3
14                                Bank Credit growth        19.375
15                                    Deposit growth          16.3
16                         Fiscal Indicators (% GDP)           NaN
17                           Centre's Fiscal Deficit      -5.33333
18                              State Fiscal Deficit      -3.66667
19                   Combined Deficit (Centre+State)            -9
20                         Inflation - WPI (Average)           4.9
21                                     CPI (Average)         3.975
22                                   Exports (US$bn)        52.575
23                                             % YoY       15.7325
24                                   Imports (US$bn)        64.675
25                                              %YoY       10.1075
26                             Trade deficit (US$bn)       -12.125
27                                Invisibles (US$bn)          17.4
28                   Current Account Deficit (US$bn)         5.275
29                                          % to GDP           0.9
30                           Capital Account (US$bn)        11.225
31                                             % GDP           2.1
32                   Forex Assets (exc. gold)(US$bn)          80.6
33                             External Debt (US$bn)       104.425
34                                   Short Term Debt          3.85
35                       Exchange Rate US$/Rs. -avg.        46.925
36                                Male in LowerHouse           494
37                              Female in LowerHouse            49
38                         Total seats contested for           543
39                                 Number of Parties            39
40                               Party with majority           BJP
41                           Majority party eats won           182

In [193]:
col1.to_csv('dt1999.csv',index=False)