In [2]:
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
from math import pi
import pandas as pd

from bokeh.io import show
from bokeh.models import (
    ColumnDataSource,
    HoverTool,
    LinearColorMapper,
    BasicTicker,
    PrintfTickFormatter,
    ColorBar,
)
from bokeh.plotting import figure
from bokeh.palettes import *

In [4]:
df1 = pd.read_csv('GE1999_detail.csv')

In [5]:
df1.rename(columns={'POLL_PERC in %':'1999POLLPERC'},inplace=True)

In [6]:
df2 = pd.read_csv('GE2004_detail.csv')

In [7]:
df2.rename(columns={'POLL_PERC in %':'2004POLLPERC'},inplace=True)

In [8]:
df3 = pd.read_csv('GE2009_detail.csv')

In [9]:
df3.rename(columns={'POLL_PERC in %':'2009POLLPERC'},inplace=True)

In [10]:
df4 = pd.read_csv('GE2014_detail.csv')

In [11]:
df4.rename(columns={'POLL_PERC in %':'2014POLLPERC'},inplace=True)

In [12]:
df4

,STATE,F,M,O,FtoM_ratio,Total voters,Total_Electors,2014POLLPERC
0,Andaman & Nicobar Islands,2.0,13.0,0.0,2.0 : 13.0,190346,269360,70.666023
1,Andhra Pradesh,43.0,555.0,0.0,43.0 : 555.0,48467721,64934138,74.641356
2,Arunachal Pradesh,0.0,11.0,0.0,0.0 : 11.0,600828,759344,79.124613
3,Assam,16.0,146.0,0.0,8.0 : 73.0,15092387,18837713,80.117937
4,Bihar,47.0,560.0,0.0,47.0 : 560.0,35892459,63800160,56.257632
5,Chandigarh,5.0,12.0,0.0,5.0 : 12.0,453462,615214,73.708011
6,Chattisgarh,21.0,190.0,0.0,21.0 : 190.0,12256962,17664520,69.387461
7,Dadra & Nagar Haveli,1.0,10.0,0.0,1.0 : 10.0,165324,196597,84.092840
8,Daman & Diu,0.0,4.0,0.0,0.0 : 4.0,87233,111827,78.007100
9,Goa,2.0,17.0,0.0,2.0 : 17.0,817440,1060777,77.060494
10,Gujarat,16.0,318.0,0.0,8.0 : 159.0,25849655,40603104,63.664234
11,Haryana,11.0,219.0,0.0,11.0 : 219.0,11501251,16097233,71.448621
12,Himachal Pradesh,5.0,33.0,0.0,5.0 : 33.0,3100199,4810071,64.452250
13,Jammu & Kashmir,3.0,74.0,0.0,3.0 : 74.0,3571537,7183129,49.721187
14,Jharkhand,18.0,222.0,0.0,3.0 : 37.0,12986625,20349796,63.816979
15,Karnataka,20.0,413.0,1.0,20.0 : 413.0,31053583,46209813,67.201274
16,Kerala,27.0,242.0,0.0,27.0 : 242.0,17987124,24326650,73.939996
17,Lakshadweep,0.0,6.0,0.0,0.0 : 6.0,43242,49922,86.619126
18,Madhya Pradesh,37.0,341.0,0.0,37.0 : 341.0,29648105,48121301,61.611188
19,Maharashtra,69.0,827.0,1.0,69.0 : 827.0,48740403,80798823,60.323160
20,Manipur,2.0,16.0,0.0,1.0 : 8.0,1415131,1774369,79.754042
21,Meghalaya,1.0,9.0,0.0,1.0 : 9.0,1078295,1567241,68.802118
22,Mizoram,0.0,3.0,0.0,0.0 : 3.0,434962,702170,61.945398
23,NCT OF Delhi,13.0,137.0,0.0,13.0 : 137.0,8275146,12711164,65.101402
24,Nagaland,0.0,3.0,0.0,0.0 : 3.0,1039962,1182972,87.910956
25,Odisha,17.0,179.0,0.0,17.0 : 179.0,21542724,29196045,73.786446
26,Puducherry,3.0,27.0,0.0,1.0 : 9.0,740053,901357,82.104316
27,Punjab,20.0,233.0,0.0,20.0 : 233.0,13849496,19608161,70.631285
28,Rajasthan,27.0,293.0,0.0,27.0 : 293.0,27133776,42994657,63.109646
29,Sikkim,0.0,6.0,0.0,0.0 : 6.0,310095,370770,83.635407
30,Tamil Nadu,55.0,790.0,1.0,11.0 : 158.0,40644282,55114867,73.744679
31,Tripura,3.0,22.0,0.0,3.0 : 22.0,2028707,2388822,84.924997
32,Uttar Pradesh,126.0,1159.0,3.0,126.0 : 1159.0,81118615,138810557,58.438361
33,Uttarakhand,7.0,67.0,0.0,7.0 : 67.0,4395561,7127057,61.674279
34,West Bengal,51.0,421.0,0.0,51.0 : 421.0,51662564,62833113,82.221876

In [13]:
df3

,STATE,TOT_CONTESTANT,Total voters,Total_Electors,2009POLLPERC,F,M,FtoM_ratio
0,Andaman & Nicobar Islands,11,170103,265108,64.163662,1.0,10.0,1.0 : 10.0
1,Andhra Pradesh,569,42083881,57892259,72.693451,39.0,530.0,39.0 : 530.0
2,Arunachal Pradesh,8,500649,734541,68.158074,0.0,8.0,0.0 : 8.0
3,Assam,158,12148928,17470329,69.540350,11.0,147.0,11.0 : 147.0
4,Bihar,672,24236704,54505246,44.466736,46.0,626.0,23.0 : 313.0
5,Chandigarh,14,343558,524444,65.508996,1.0,13.0,1.0 : 13.0
6,Chattisgarh,178,8556920,15476577,55.289487,15.0,163.0,15.0 : 163.0
7,Dadra & Nagar Haveli,5,110363,150704,73.231633,0.0,5.0,0.0 : 5.0
8,Daman & Diu,7,68025,95382,71.318488,0.0,7.0,0.0 : 7.0
9,Goa,18,564439,1020794,55.294114,2.0,16.0,1.0 : 8.0
10,Gujarat,359,17476567,36484281,47.901635,26.0,333.0,26.0 : 333.0
11,Haryana,210,8160347,12087710,67.509454,14.0,196.0,1.0 : 14.0
12,Himachal Pradesh,31,2691573,4606674,58.427686,1.0,30.0,1.0 : 30.0
13,Jammu & Kashmir,81,2609249,6572896,39.697099,6.0,75.0,2.0 : 25.0
14,Jharkhand,249,9142643,17934095,50.979115,14.0,235.0,14.0 : 235.0
15,Karnataka,427,24581348,41790939,58.819803,19.0,408.0,19.0 : 408.0
16,Kerala,217,16041499,21859536,73.384444,15.0,202.0,15.0 : 202.0
17,Lakshadweep,4,39498,45983,85.896962,0.0,4.0,0.0 : 4.0
18,Madhya Pradesh,429,19488631,38085179,51.171168,29.0,400.0,29.0 : 400.0
19,Maharashtra,819,37007318,72954058,50.726881,55.0,764.0,55.0 : 764.0
20,Manipur,16,1342309,1736251,77.310769,3.0,13.0,3.0 : 13.0
21,Meghalaya,11,822614,1277739,64.380441,3.0,8.0,3.0 : 8.0
22,Mizoram,4,326424,629374,51.864869,0.0,4.0,0.0 : 4.0
23,NCT OF Delhi,160,5754353,11096854,51.855715,18.0,142.0,9.0 : 71.0
24,Nagaland,3,1189742,1321878,90.003919,0.0,3.0,0.0 : 3.0
25,Orissa,157,17772023,27194864,65.350660,9.0,148.0,9.0 : 148.0
26,Puducherry,28,608509,762440,79.810739,0.0,28.0,0.0 : 28.0
27,Punjab,218,11833883,16958380,69.781919,13.0,205.0,13.0 : 205.0
28,Rajasthan,346,17942008,37060011,48.413391,31.0,315.0,31.0 : 315.0
29,Sikkim,7,252274,300584,83.927954,0.0,7.0,0.0 : 7.0
30,Tamil Nadu,823,30404136,41620460,73.050937,48.0,775.0,48.0 : 775.0
31,Tripura,19,1760485,2082265,84.546636,1.0,18.0,1.0 : 18.0
32,Uttar Pradesh,1368,55434443,116006374,47.785687,100.0,1268.0,25.0 : 317.0
33,Uttarakhand,76,3145818,5887724,53.430120,7.0,69.0,7.0 : 69.0
34,West Bengal,368,42740385,52493168,81.420853,29.0,339.0,29.0 : 339.0

In [14]:
m=pd.merge(df1,df2,on='STATE',how='outer')

In [15]:
m.columns

Index(['STATE', 'TOT_CONTESTANT_x', 'TOT_ELECTORS_x', 'TOT_VOTERS_x',
       '1999POLLPERC', 'F_x', 'M_x', 'FtoM_ratio_x', 'TOT_CONTESTANT_y',
       'TOT_ELECTORS_y', 'TOT_VOTERS_y', '2004POLLPERC', 'F_y', 'M_y',
       'FtoM_ratio_y'],
      dtype='object')

In [16]:
del m['TOT_CONTESTANT_x']

In [17]:
del m['TOT_ELECTORS_x']

In [18]:
del m['TOT_VOTERS_x']

In [19]:
del m['F_x']

In [20]:
del m['M_x']

In [21]:
del m['F_y']

In [22]:
del m['M_y']

In [23]:
del m['TOT_ELECTORS_y']
del m['TOT_VOTERS_y']

In [24]:
del m['FtoM_ratio_y']

In [25]:
del m['FtoM_ratio_x']

In [26]:
def getlow(x):
    for i in x["STATE"]:
        return i.lower()

In [27]:
m["STATE"]= m['STATE'].apply(lambda x: x.lower())

In [28]:
m['STATE'][22]='nct of delhi'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [29]:
del m['TOT_CONTESTANT_y']

In [30]:
y=df3.pivot_table(index='STATE',values='2009POLLPERC')

In [31]:
z=df4.pivot_table(index='STATE',values='2014POLLPERC')

In [32]:
z.reset_index(inplace=True)

In [33]:
y.reset_index(inplace=True)

In [34]:
z["STATE"][25]='Orissa'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
n=pd.merge(y,z,on="STATE",how='outer')

In [36]:
m

                        STATE  1999POLLPERC  2004POLLPERC
0   andaman & nicobar islands     59.463021     63.664053
1              andhra pradesh     69.142071     69.948844
2           arunachal pradesh     72.147024     56.348953
3                       assam     71.255699     69.113827
4                       bihar     61.480594     58.015222
5                  chandigarh     48.354889     51.138371
6        dadra & nagar haveli     74.720460     69.043291
7                 daman & diu     71.744489     70.162308
8                         goa     45.105843     58.767998
9                     gujarat     47.026369     45.177351
10                    haryana     63.683238     65.719951
11           himachal pradesh     56.776124     59.711908
12            jammu & kashmir     32.344227     35.202395
13                  karnataka     67.577502     65.140599
14                     kerala     70.187885     71.449098
15                lakshadweep     80.209469     81.520764
16             madhya pradesh     54.879174     48.094302
17                maharashtra     60.964043     54.375681
18                    manipur     65.671966     67.405744
19                  meghalaya     56.155909     52.686110
20                    mizoram     65.311322     63.604560
21                   nagaland     76.245666     91.766825
22               nct of delhi     43.543001     47.086835
23                     orissa     55.634272     66.057614
24                pondicherry     63.273551     76.073677
25                     punjab     56.111404     61.588440
26                  rajasthan     53.860198     49.972219
27                     sikkim     81.710569     77.949684
28                 tamil nadu     57.981183     60.807562
29                    tripura     68.137334     67.080439
30              uttar pradesh     53.530726     48.161190
31                west bengal     75.049927     78.042755
32               chhattisgarh           NaN     52.088044
33                  jharkhand           NaN     55.693399
34                uttaranchal           NaN     48.067706

In [37]:
n["STATE"]= n['STATE'].apply(lambda x: x.lower())

In [38]:
n

                        STATE  2009POLLPERC  2014POLLPERC
0   andaman & nicobar islands     64.163662     70.666023
1              andhra pradesh     72.693451     74.641356
2           arunachal pradesh     68.158074     79.124613
3                       assam     69.540350     80.117937
4                       bihar     44.466736     56.257632
5                  chandigarh     65.508996     73.708011
6                 chattisgarh     55.289487     69.387461
7        dadra & nagar haveli     73.231633     84.092840
8                 daman & diu     71.318488     78.007100
9                         goa     55.294114     77.060494
10                    gujarat     47.901635     63.664234
11                    haryana     67.509454     71.448621
12           himachal pradesh     58.427686     64.452250
13            jammu & kashmir     39.697099     49.721187
14                  jharkhand     50.979115     63.816979
15                  karnataka     58.819803     67.201274
16                     kerala     73.384444     73.939996
17                lakshadweep     85.896962     86.619126
18             madhya pradesh     51.171168     61.611188
19                maharashtra     50.726881     60.323160
20                    manipur     77.310769     79.754042
21                  meghalaya     64.380441     68.802118
22                    mizoram     51.864869     61.945398
23               nct of delhi     51.855715     65.101402
24                   nagaland     90.003919     87.910956
25                     orissa     65.350660     73.786446
26                 puducherry     79.810739     82.104316
27                     punjab     69.781919     70.631285
28                  rajasthan     48.413391     63.109646
29                     sikkim     83.927954     83.635407
30                 tamil nadu     73.050937     73.744679
31                    tripura     84.546636     84.924997
32              uttar pradesh     47.785687     58.438361
33                uttarakhand     53.430120     61.674279
34                west bengal     81.420853     82.221876

In [39]:
m["STATE"][34]="uttarakhand"

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [40]:
m["STATE"][32]='chattisgarh'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [41]:
m["STATE"][24]='puducherry'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [42]:
m

                        STATE  1999POLLPERC  2004POLLPERC
0   andaman & nicobar islands     59.463021     63.664053
1              andhra pradesh     69.142071     69.948844
2           arunachal pradesh     72.147024     56.348953
3                       assam     71.255699     69.113827
4                       bihar     61.480594     58.015222
5                  chandigarh     48.354889     51.138371
6        dadra & nagar haveli     74.720460     69.043291
7                 daman & diu     71.744489     70.162308
8                         goa     45.105843     58.767998
9                     gujarat     47.026369     45.177351
10                    haryana     63.683238     65.719951
11           himachal pradesh     56.776124     59.711908
12            jammu & kashmir     32.344227     35.202395
13                  karnataka     67.577502     65.140599
14                     kerala     70.187885     71.449098
15                lakshadweep     80.209469     81.520764
16             madhya pradesh     54.879174     48.094302
17                maharashtra     60.964043     54.375681
18                    manipur     65.671966     67.405744
19                  meghalaya     56.155909     52.686110
20                    mizoram     65.311322     63.604560
21                   nagaland     76.245666     91.766825
22               nct of delhi     43.543001     47.086835
23                     orissa     55.634272     66.057614
24                 puducherry     63.273551     76.073677
25                     punjab     56.111404     61.588440
26                  rajasthan     53.860198     49.972219
27                     sikkim     81.710569     77.949684
28                 tamil nadu     57.981183     60.807562
29                    tripura     68.137334     67.080439
30              uttar pradesh     53.530726     48.161190
31                west bengal     75.049927     78.042755
32                chattisgarh           NaN     52.088044
33                  jharkhand           NaN     55.693399
34                uttarakhand           NaN     48.067706

In [43]:
n

                        STATE  2009POLLPERC  2014POLLPERC
0   andaman & nicobar islands     64.163662     70.666023
1              andhra pradesh     72.693451     74.641356
2           arunachal pradesh     68.158074     79.124613
3                       assam     69.540350     80.117937
4                       bihar     44.466736     56.257632
5                  chandigarh     65.508996     73.708011
6                 chattisgarh     55.289487     69.387461
7        dadra & nagar haveli     73.231633     84.092840
8                 daman & diu     71.318488     78.007100
9                         goa     55.294114     77.060494
10                    gujarat     47.901635     63.664234
11                    haryana     67.509454     71.448621
12           himachal pradesh     58.427686     64.452250
13            jammu & kashmir     39.697099     49.721187
14                  jharkhand     50.979115     63.816979
15                  karnataka     58.819803     67.201274
16                     kerala     73.384444     73.939996
17                lakshadweep     85.896962     86.619126
18             madhya pradesh     51.171168     61.611188
19                maharashtra     50.726881     60.323160
20                    manipur     77.310769     79.754042
21                  meghalaya     64.380441     68.802118
22                    mizoram     51.864869     61.945398
23               nct of delhi     51.855715     65.101402
24                   nagaland     90.003919     87.910956
25                     orissa     65.350660     73.786446
26                 puducherry     79.810739     82.104316
27                     punjab     69.781919     70.631285
28                  rajasthan     48.413391     63.109646
29                     sikkim     83.927954     83.635407
30                 tamil nadu     73.050937     73.744679
31                    tripura     84.546636     84.924997
32              uttar pradesh     47.785687     58.438361
33                uttarakhand     53.430120     61.674279
34                west bengal     81.420853     82.221876

In [44]:
poll=pd.merge(n,m,on='STATE')

In [45]:
poll.fillna(value=0,inplace=True)

In [46]:
t=list(poll.columns)

In [47]:
t[1]='2009'

In [48]:
t[2]='2014'

In [49]:
t[3]='1999'

In [50]:
t[4]='2004'

In [51]:
poll.columns=t

In [52]:
poll

                        STATE       2009       2014       1999       2004
0   andaman & nicobar islands  64.163662  70.666023  59.463021  63.664053
1              andhra pradesh  72.693451  74.641356  69.142071  69.948844
2           arunachal pradesh  68.158074  79.124613  72.147024  56.348953
3                       assam  69.540350  80.117937  71.255699  69.113827
4                       bihar  44.466736  56.257632  61.480594  58.015222
5                  chandigarh  65.508996  73.708011  48.354889  51.138371
6                 chattisgarh  55.289487  69.387461   0.000000  52.088044
7        dadra & nagar haveli  73.231633  84.092840  74.720460  69.043291
8                 daman & diu  71.318488  78.007100  71.744489  70.162308
9                         goa  55.294114  77.060494  45.105843  58.767998
10                    gujarat  47.901635  63.664234  47.026369  45.177351
11                    haryana  67.509454  71.448621  63.683238  65.719951
12           himachal pradesh  58.427686  64.452250  56.776124  59.711908
13            jammu & kashmir  39.697099  49.721187  32.344227  35.202395
14                  jharkhand  50.979115  63.816979   0.000000  55.693399
15                  karnataka  58.819803  67.201274  67.577502  65.140599
16                     kerala  73.384444  73.939996  70.187885  71.449098
17                lakshadweep  85.896962  86.619126  80.209469  81.520764
18             madhya pradesh  51.171168  61.611188  54.879174  48.094302
19                maharashtra  50.726881  60.323160  60.964043  54.375681
20                    manipur  77.310769  79.754042  65.671966  67.405744
21                  meghalaya  64.380441  68.802118  56.155909  52.686110
22                    mizoram  51.864869  61.945398  65.311322  63.604560
23               nct of delhi  51.855715  65.101402  43.543001  47.086835
24                   nagaland  90.003919  87.910956  76.245666  91.766825
25                     orissa  65.350660  73.786446  55.634272  66.057614
26                 puducherry  79.810739  82.104316  63.273551  76.073677
27                     punjab  69.781919  70.631285  56.111404  61.588440
28                  rajasthan  48.413391  63.109646  53.860198  49.972219
29                     sikkim  83.927954  83.635407  81.710569  77.949684
30                 tamil nadu  73.050937  73.744679  57.981183  60.807562
31                    tripura  84.546636  84.924997  68.137334  67.080439
32              uttar pradesh  47.785687  58.438361  53.530726  48.161190
33                uttarakhand  53.430120  61.674279   0.000000  48.067706
34                west bengal  81.420853  82.221876  75.049927  78.042755

In [53]:
poll=poll[['STATE','1999','2004','2009','2014']]

In [54]:
poll

                        STATE       1999       2004       2009       2014
0   andaman & nicobar islands  59.463021  63.664053  64.163662  70.666023
1              andhra pradesh  69.142071  69.948844  72.693451  74.641356
2           arunachal pradesh  72.147024  56.348953  68.158074  79.124613
3                       assam  71.255699  69.113827  69.540350  80.117937
4                       bihar  61.480594  58.015222  44.466736  56.257632
5                  chandigarh  48.354889  51.138371  65.508996  73.708011
6                 chattisgarh   0.000000  52.088044  55.289487  69.387461
7        dadra & nagar haveli  74.720460  69.043291  73.231633  84.092840
8                 daman & diu  71.744489  70.162308  71.318488  78.007100
9                         goa  45.105843  58.767998  55.294114  77.060494
10                    gujarat  47.026369  45.177351  47.901635  63.664234
11                    haryana  63.683238  65.719951  67.509454  71.448621
12           himachal pradesh  56.776124  59.711908  58.427686  64.452250
13            jammu & kashmir  32.344227  35.202395  39.697099  49.721187
14                  jharkhand   0.000000  55.693399  50.979115  63.816979
15                  karnataka  67.577502  65.140599  58.819803  67.201274
16                     kerala  70.187885  71.449098  73.384444  73.939996
17                lakshadweep  80.209469  81.520764  85.896962  86.619126
18             madhya pradesh  54.879174  48.094302  51.171168  61.611188
19                maharashtra  60.964043  54.375681  50.726881  60.323160
20                    manipur  65.671966  67.405744  77.310769  79.754042
21                  meghalaya  56.155909  52.686110  64.380441  68.802118
22                    mizoram  65.311322  63.604560  51.864869  61.945398
23               nct of delhi  43.543001  47.086835  51.855715  65.101402
24                   nagaland  76.245666  91.766825  90.003919  87.910956
25                     orissa  55.634272  66.057614  65.350660  73.786446
26                 puducherry  63.273551  76.073677  79.810739  82.104316
27                     punjab  56.111404  61.588440  69.781919  70.631285
28                  rajasthan  53.860198  49.972219  48.413391  63.109646
29                     sikkim  81.710569  77.949684  83.927954  83.635407
30                 tamil nadu  57.981183  60.807562  73.050937  73.744679
31                    tripura  68.137334  67.080439  84.546636  84.924997
32              uttar pradesh  53.530726  48.161190  47.785687  58.438361
33                uttarakhand   0.000000  48.067706  53.430120  61.674279
34                west bengal  75.049927  78.042755  81.420853  82.221876

In [55]:
poll['STATE']= poll['STATE'].apply(lambda x: x.upper())

In [56]:
poll.set_index('STATE',inplace=True)

In [57]:
poll

                                1999       2004       2009       2014
STATE
ANDAMAN & NICOBAR ISLANDS  59.463021  63.664053  64.163662  70.666023
ANDHRA PRADESH             69.142071  69.948844  72.693451  74.641356
ARUNACHAL PRADESH          72.147024  56.348953  68.158074  79.124613
ASSAM                      71.255699  69.113827  69.540350  80.117937
BIHAR                      61.480594  58.015222  44.466736  56.257632
CHANDIGARH                 48.354889  51.138371  65.508996  73.708011
CHATTISGARH                 0.000000  52.088044  55.289487  69.387461
DADRA & NAGAR HAVELI       74.720460  69.043291  73.231633  84.092840
DAMAN & DIU                71.744489  70.162308  71.318488  78.007100
GOA                        45.105843  58.767998  55.294114  77.060494
GUJARAT                    47.026369  45.177351  47.901635  63.664234
HARYANA                    63.683238  65.719951  67.509454  71.448621
HIMACHAL PRADESH           56.776124  59.711908  58.427686  64.452250
JAMMU & KASHMIR            32.344227  35.202395  39.697099  49.721187
JHARKHAND                   0.000000  55.693399  50.979115  63.816979
KARNATAKA                  67.577502  65.140599  58.819803  67.201274
KERALA                     70.187885  71.449098  73.384444  73.939996
LAKSHADWEEP                80.209469  81.520764  85.896962  86.619126
MADHYA PRADESH             54.879174  48.094302  51.171168  61.611188
MAHARASHTRA                60.964043  54.375681  50.726881  60.323160
MANIPUR                    65.671966  67.405744  77.310769  79.754042
MEGHALAYA                  56.155909  52.686110  64.380441  68.802118
MIZORAM                    65.311322  63.604560  51.864869  61.945398
NCT OF DELHI               43.543001  47.086835  51.855715  65.101402
NAGALAND                   76.245666  91.766825  90.003919  87.910956
ORISSA                     55.634272  66.057614  65.350660  73.786446
PUDUCHERRY                 63.273551  76.073677  79.810739  82.104316
PUNJAB                     56.111404  61.588440  69.781919  70.631285
RAJASTHAN                  53.860198  49.972219  48.413391  63.109646
SIKKIM                     81.710569  77.949684  83.927954  83.635407
TAMIL NADU                 57.981183  60.807562  73.050937  73.744679
TRIPURA                    68.137334  67.080439  84.546636  84.924997
UTTAR PRADESH              53.530726  48.161190  47.785687  58.438361
UTTARAKHAND                 0.000000  48.067706  53.430120  61.674279
WEST BENGAL                75.049927  78.042755  81.420853  82.221876

In [58]:
states=list(poll.index)

In [59]:
year=list(poll.columns)

In [60]:
df = pd.DataFrame(poll.stack(), columns=['rate']).reset_index()

In [61]:
df

                         STATE level_1       rate
0    ANDAMAN & NICOBAR ISLANDS    1999  59.463021
1    ANDAMAN & NICOBAR ISLANDS    2004  63.664053
2    ANDAMAN & NICOBAR ISLANDS    2009  64.163662
3    ANDAMAN & NICOBAR ISLANDS    2014  70.666023
4               ANDHRA PRADESH    1999  69.142071
5               ANDHRA PRADESH    2004  69.948844
6               ANDHRA PRADESH    2009  72.693451
7               ANDHRA PRADESH    2014  74.641356
8            ARUNACHAL PRADESH    1999  72.147024
9            ARUNACHAL PRADESH    2004  56.348953
10           ARUNACHAL PRADESH    2009  68.158074
11           ARUNACHAL PRADESH    2014  79.124613
12                       ASSAM    1999  71.255699
13                       ASSAM    2004  69.113827
14                       ASSAM    2009  69.540350
15                       ASSAM    2014  80.117937
16                       BIHAR    1999  61.480594
17                       BIHAR    2004  58.015222
18                       BIHAR    2009  44.466736
19                       BIHAR    2014  56.257632
20                  CHANDIGARH    1999  48.354889
21                  CHANDIGARH    2004  51.138371
22                  CHANDIGARH    2009  65.508996
23                  CHANDIGARH    2014  73.708011
24                 CHATTISGARH    1999   0.000000
25                 CHATTISGARH    2004  52.088044
26                 CHATTISGARH    2009  55.289487
27                 CHATTISGARH    2014  69.387461
28        DADRA & NAGAR HAVELI    1999  74.720460
29        DADRA & NAGAR HAVELI    2004  69.043291
..                         ...     ...        ...
110                     PUNJAB    2009  69.781919
111                     PUNJAB    2014  70.631285
112                  RAJASTHAN    1999  53.860198
113                  RAJASTHAN    2004  49.972219
114                  RAJASTHAN    2009  48.413391
115                  RAJASTHAN    2014  63.109646
116                     SIKKIM    1999  81.710569
117                     SIKKIM    2004  77.949684
118                     SIKKIM    2009  83.927954
119                     SIKKIM    2014  83.635407
120                 TAMIL NADU    1999  57.981183
121                 TAMIL NADU    2004  60.807562
122                 TAMIL NADU    2009  73.050937
123                 TAMIL NADU    2014  73.744679
124                    TRIPURA    1999  68.137334
125                    TRIPURA    2004  67.080439
126                    TRIPURA    2009  84.546636
127                    TRIPURA    2014  84.924997
128              UTTAR PRADESH    1999  53.530726
129              UTTAR PRADESH    2004  48.161190
130              UTTAR PRADESH    2009  47.785687
131              UTTAR PRADESH    2014  58.438361
132                UTTARAKHAND    1999   0.000000
133                UTTARAKHAND    2004  48.067706
134                UTTARAKHAND    2009  53.430120
135                UTTARAKHAND    2014  61.674279
136                WEST BENGAL    1999  75.049927
137                WEST BENGAL    2004  78.042755
138                WEST BENGAL    2009  81.420853
139                WEST BENGAL    2014  82.221876

[140 rows x 3 columns]

In [62]:
colors = Reds9
colors = colors[::-1]
mapper = LinearColorMapper(palette=colors, low=df.rate.min(), high=df.rate.max())

source = ColumnDataSource(df)

TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"

In [63]:
p = figure(title="STATEWISE VOTER TURNOUT PATTERN ({0} - {1})".format(states[0], states[-1]),
           x_range=states, y_range=list(reversed(year)),
           x_axis_location="below", plot_width=950, plot_height=650,
           tools=TOOLS, toolbar_location='above')

In [64]:
p.grid.grid_line_color = None
p.axis.axis_line_color = None
p.axis.major_tick_line_color = None
p.axis.major_label_text_font_size = "8pt"
p.axis.major_label_standoff = 0
p.xaxis.major_label_orientation = pi / 3
p.xaxis.axis_label = 'STATES'
p.yaxis.axis_label = 'GENERAL ELECTION YEAR'

In [65]:
p.rect(x="STATE", y="level_1", width=1, height=1,
       source=source,
       fill_color={'field': 'rate', 'transform': mapper},
       line_color=None)

GlyphRenderer(id='8f335d92-fc19-4ea5-8e4d-dbe04975d7fe', ...)

In [66]:
color_bar = ColorBar(color_mapper= mapper, major_label_text_font_size="8pt",
                     ticker= BasicTicker(desired_num_ticks=len(colors)),
                     formatter= PrintfTickFormatter(format="%d%%"),
                     label_standoff=7, border_line_color=None, location=(0, 0))
p.add_layout(color_bar, 'right')

In [67]:
p.select_one(HoverTool).tooltips = [
     ('State', '@STATE in @level_1'),
     ('Voters Turnout%', '@rate%'),
]

In [68]:
from bokeh.plotting import *

output_file("POLLING STATISTICS.html")

In [69]:
show(p)